import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface Translations {
  [key: string]: {
    en: string;
    es: string;
  };
}

const translations: Translations = {
  // Header
  opportunityInvestorAnalysis: { en: 'Opportunity Investor Analysis', es: 'Análisis de Inversionista de Oportunidad' },
  exitScenariosPaymentBreakdown: { en: 'Exit scenarios & payment breakdown', es: 'Escenarios de salida y desglose de pagos' },
  
  // Client Info
  clientUnitInfo: { en: 'Client & Unit Information', es: 'Información del Cliente y Unidad' },
  clientDetails: { en: 'Client Details', es: 'Datos del Cliente' },
  developer: { en: 'Developer', es: 'Desarrollador' },
  clientName: { en: 'Client Name', es: 'Nombre del Cliente' },
  client: { en: 'Client', es: 'Cliente' },
  clientCountry: { en: 'Client Country', es: 'País del Cliente' },
  country: { en: 'Country', es: 'País' },
  advisorName: { en: 'Advisor Name', es: 'Nombre del Asesor' },
  advisor: { en: 'Advisor', es: 'Asesor' },
  unit: { en: 'Unit', es: 'Unidad' },
  unitSize: { en: 'Unit Size (sqf)', es: 'Tamaño (sqf)' },
  unitSizeSqf: { en: 'Size (sqf)', es: 'Tamaño (sqf)' },
  unitSizeM2: { en: 'Size (m²)', es: 'Tamaño (m²)' },
  size: { en: 'Size', es: 'Tamaño' },
  unitType: { en: 'Unit Type', es: 'Tipo de Unidad' },
  purchasePrice: { en: 'Purchase Price', es: 'Precio de Compra' },
  clickToAddClientInfo: { en: 'Click to add client & unit information', es: 'Clic para agregar información del cliente y unidad' },
  save: { en: 'Save', es: 'Guardar' },
  zone: { en: 'Zone', es: 'Zona' },
  selectZone: { en: 'Select zone...', es: 'Seleccionar zona...' },
  noZones: { en: 'No zones available', es: 'No hay zonas disponibles' },
  searchQuotes: { en: 'Search quotes...', es: 'Buscar cotizaciones...' },
  pricePerSqft: { en: 'Price/sqft', es: 'Precio/sqft' },
  
  // Month names for configurator
  january: { en: 'January', es: 'Enero' },
  february: { en: 'February', es: 'Febrero' },
  march: { en: 'March', es: 'Marzo' },
  april: { en: 'April', es: 'Abril' },
  may: { en: 'May', es: 'Mayo' },
  june: { en: 'June', es: 'Junio' },
  july: { en: 'July', es: 'Julio' },
  august: { en: 'August', es: 'Agosto' },
  september: { en: 'September', es: 'Septiembre' },
  october: { en: 'October', es: 'Octubre' },
  november: { en: 'November', es: 'Noviembre' },
  december: { en: 'December', es: 'Diciembre' },
  
  // Configurator sections (additional translations)
  bookingDateOI: { en: 'Booking Date (OI Entry)', es: 'Fecha de Reserva (Entrada OI)' },
  handoverDateLabel: { en: 'Handover Date', es: 'Fecha de Entrega' },
  paymentPlanLabel: { en: 'Payment Plan', es: 'Plan de Pago' },
  downpaymentLabel: { en: 'DOWNPAYMENT (Booking - Month 0)', es: 'ENGANCHE (Reserva - Mes 0)' },
  autoGeneratePayments: { en: 'Auto-Generate Payments', es: 'Generar Pagos Automáticamente' },
  numberOfPayments: { en: 'Number of Payments', es: 'Número de Pagos' },
  intervalMonths: { en: 'Interval (months)', es: 'Intervalo (meses)' },
  generatePayments: { en: 'Generate Payments', es: 'Generar Pagos' },
  additionalPayments: { en: 'Additional Payments (Pre-Handover)', es: 'Pagos Adicionales (Pre-Entrega)' },
  handoverPaymentLabel: { en: 'HANDOVER (100% Construction)', es: 'ENTREGA (100% Construcción)' },
  minimumExitThresholdLabel: { en: 'Minimum Exit Threshold', es: 'Umbral Mínimo de Salida' },
  rentalStrategy: { en: 'Rental Strategy', es: 'Estrategia de Renta' },
  longTermRentalLabel: { en: 'Long-Term Rental', es: 'Renta a Largo Plazo' },
  rentalYieldPercent: { en: 'Rental Yield %', es: 'Rendimiento de Renta %' },
  estimatedAnnualRentLabel: { en: 'Est. Annual Rent', es: 'Renta Anual Est.' },
  compareWithShortTerm: { en: 'Compare with Short-Term', es: 'Comparar con Corto Plazo' },
  zoneAppreciation: { en: 'Zone & Appreciation', es: 'Zona y Apreciación' },
  appreciationSettings: { en: 'Appreciation Settings', es: 'Configuración de Apreciación' },
  useZoneDefaults: { en: 'Use zone defaults', es: 'Usar valores de zona' },
  customAppreciation: { en: 'Custom appreciation', es: 'Apreciación personalizada' },
  resetToDefaults: { en: 'Reset to Defaults', es: 'Restablecer Valores' },
  handoverMustBeAfterBooking: { en: 'Handover date must be after booking date', es: 'Fecha de entrega debe ser después de la fecha de reserva' },
  eoiPartOfThis: { en: 'EOI is part of this', es: 'EOI es parte de esto' },
  remainingLabel: { en: 'remaining', es: 'restante' },
  exceededLabel: { en: 'exceeded', es: 'excedido' },
  distributed: { en: 'Distributed', es: 'Distribuido' },
  addPaymentBtn: { en: 'Add Payment', es: 'Agregar Pago' },
  timeLabel: { en: 'Time', es: 'Tiempo' },
  constructionLabelShort: { en: 'Const.', es: 'Const.' },
  automatic: { en: 'Automatic', es: 'Automático' },
  
  // Unit Types
  studio: { en: 'Studio', es: 'Estudio' },
  oneBed: { en: '1 Bedroom', es: '1 Habitación' },
  twoBed: { en: '2 Bedrooms', es: '2 Habitaciones' },
  threeBed: { en: '3 Bedrooms', es: '3 Habitaciones' },
  fourBed: { en: '4 Bedrooms', es: '4 Habitaciones' },
  penthouse: { en: 'Penthouse', es: 'Penthouse' },
  
  // Investment Summary
  investmentSummary: { en: 'Investment Summary', es: 'Resumen de Inversión' },
  basePropertyPrice: { en: 'Base Property Price', es: 'Precio Base de Propiedad' },
  paymentPlan: { en: 'Payment Plan', es: 'Plan de Pago' },
  downpayment: { en: 'Downpayment', es: 'Enganche' },
  additional: { en: 'additional', es: 'adicionales' },
  constructionPeriod: { en: 'Construction Period', es: 'Período de Construcción' },
  appreciationRate: { en: 'Appreciation Rate (CAGR)', es: 'Tasa de Apreciación (CAGR)' },
  rentalYield: { en: 'Rental Yield', es: 'Rendimiento de Renta' },
  minimumExitThreshold: { en: 'Min Exit Threshold', es: 'Umbral Mín de Salida' },
  totalEntryCosts: { en: 'Total Entry Costs', es: 'Costos Totales de Entrada' },
  bestROE: { en: 'Best ROE', es: 'Mejor ROE' },
  profit: { en: 'Profit', es: 'Ganancia' },
  grossProfit: { en: 'Gross Profit', es: 'Ganancia Bruta' },
  netProfit: { en: 'Net Profit', es: 'Ganancia Neta' },
  agentCommission: { en: 'Agent (2%)', es: 'Agente (2%)' },
  nocFee: { en: 'NOC Fee', es: 'Tasa NOC' },
  capital: { en: 'Capital', es: 'Capital' },
  atHandover: { en: 'At Handover', es: 'En Entrega' },
  
  // Hold Analysis
  ifYouHoldAfterHandover: { en: 'If You HOLD After Handover', es: 'Si MANTIENE Después de Entrega' },
  totalCapitalInvested: { en: 'Total Capital Invested', es: 'Capital Total Invertido' },
  valueAtHandover: { en: 'Value at Handover', es: 'Valor en Entrega' },
  annualRentEst: { en: 'Annual Rent (Est.)', es: 'Renta Anual (Est.)' },
  rentalYieldOnInvestment: { en: 'Rental Yield on Investment', es: 'Rendimiento de Renta sobre Inversión' },
  yearsToBreakEven: { en: 'Years to Break Even', es: 'Años para Recuperar' },
  holdingMeansFullPayment: { en: 'Holding means full property payment + rental income', es: 'Mantener significa pago completo + ingresos de renta' },
  
  // Navigation
  fullROICalculator: { en: 'Full ROI Calculator (OI → SI → HO)', es: 'Calculadora ROI Completa (OI → SI → HO)' },
  
  // Modal
  configure: { en: 'Configure', es: 'Configurar' },
  oiInvestmentParameters: { en: 'OI Investment Parameters', es: 'Parámetros de Inversión OI' },
  bookingDate: { en: 'Booking Date (OI Entry)', es: 'Fecha de Reserva (Entrada OI)' },
  handoverDate: { en: 'Handover Date', es: 'Fecha de Entrega' },
  entryCostsAtBooking: { en: 'Entry Costs (At Booking)', es: 'Costos de Entrada (En Reserva)' },
  eoiBookingFee: { en: 'EOI / Booking Fee', es: 'EOI / Cuota de Reserva' },
  dldFeeFixed: { en: 'DLD Fee (fixed)', es: 'Tarifa DLD (fija)' },
  oqoodFee: { en: 'Oqood Fee', es: 'Tarifa Oqood' },
  minExitThresholdDesc: { en: '% of price developer requires paid before allowing resale', es: '% del precio que el developer exige haber pagado para permitir reventa' },
  preHandoverSplit: { en: 'Pre-Handover / Handover Split', es: 'División Pre-Entrega / Entrega' },
  eoiIsPartOfThis: { en: 'EOI is part of this', es: 'EOI es parte de esto' },
  addPayment: { en: 'Add Payment', es: 'Agregar Pago' },
  timeBasedMonth: { en: 'Time-based (Month)', es: 'Basado en Tiempo (Mes)' },
  constructionBased: { en: 'Construction %', es: 'Construcción %' },
  handoverPaymentAuto: { en: 'Handover Payment (Automatic)', es: 'Pago de Entrega (Automático)' },
  atHandoverDate: { en: 'At handover date', es: 'En fecha de entrega' },
  financialMetrics: { en: 'Financial Metrics', es: 'Métricas Financieras' },
  applyParameters: { en: 'Apply Parameters', es: 'Aplicar Parámetros' },
  
  // Validation
  preHandoverMustEqual: { en: 'Pre-handover payments must equal', es: 'Pagos pre-entrega deben ser igual a' },
  youNeedToAdd: { en: 'You need to add', es: 'Necesita agregar' },
  moreViaAdditional: { en: 'more via additional payments', es: 'más vía pagos adicionales' },
  validPreHandover: { en: 'Valid pre-handover distribution', es: 'Distribución pre-entrega válida' },
  
  // Select placeholders
  selectCountry: { en: 'Select country', es: 'Seleccionar país' },
  selectType: { en: 'Select type', es: 'Seleccionar tipo' },
  
  // New fields
  projectName: { en: 'Project Name', es: 'Nombre del Proyecto' },
  accountSettings: { en: 'Account Settings', es: 'Configuración de Cuenta' },
  myQuotes: { en: 'My Quotes', es: 'Mis Cotizaciones' },
  newQuote: { en: 'New Quote', es: 'Nueva Cotización' },
  wealthAdvisor: { en: 'Wealth Advisor', es: 'Asesor de Patrimonio' },
  clients: { en: 'Clients', es: 'Clientes' },
  addClient: { en: 'Add Client', es: 'Agregar Cliente' },
  cashflowStatement: { en: 'Cashflow Generator', es: 'Generador de Cashflow' },
  investmentSnapshot: { en: 'Investment Snapshot', es: 'Resumen de Inversión' },
  amountUntilSPA: { en: 'At Booking (SPA)', es: 'En Reserva (SPA)' },
  amountDuringConstruction: { en: 'During Construction', es: 'Durante Construcción' },
  amountAtHandover: { en: 'At Handover', es: 'En Entrega' },
  paybackPeriod: { en: 'Payback Period', es: 'Período de Recuperación' },
  paybackPeriodDesc: { en: 'Time to recover investment from rental income', es: 'Tiempo para recuperar inversión con ingresos de renta' },
  longTermRental: { en: 'Long-Term Rental', es: 'Renta a Largo Plazo' },
  basedOnNetRentalIncome: { en: 'Based on net rental income', es: 'Basado en renta neta' },
  
  // Rent Snapshot
  rentSnapshot: { en: 'Rent Snapshot', es: 'Resumen de Renta' },
  estimatedAnnualRent: { en: 'Est. Annual Rent (Y1)', es: 'Renta Anual Est. (A1)' },
  rentGrowth: { en: 'Rent Growth', es: 'Crecimiento Renta' },
  serviceCharges: { en: 'Service Charges', es: 'Cargos de Servicio' },
  netAnnualRent: { en: 'Net Annual Rent', es: 'Renta Anual Neta' },
  shortTermComparison: { en: 'Short-Term Comparison', es: 'Comparación Corto Plazo' },
  averageDailyRate: { en: 'Average Daily Rate', es: 'Tarifa Diaria Promedio' },
  occupancy: { en: 'Occupancy', es: 'Ocupación' },
  adrGrowth: { en: 'ADR Growth', es: 'Crecimiento ADR' },
  grossAnnual: { en: 'Gross Annual', es: 'Bruto Anual' },
  utilitiesAndUpkeep: { en: 'Utilities & Upkeep', es: 'Servicios y Mantenimiento' },
  managementFee: { en: 'Management Fee', es: 'Comisión de Gestión' },
  netAnnual: { en: 'Net Annual', es: 'Neto Anual' },
  basedOnOccupancy: { en: 'Based on', es: 'Basado en' },
  occupancyEst: { en: 'Occupancy Est.', es: 'Ocupación Est.' },
  scenarioPlayground: { en: 'Scenario Playground', es: 'Simulador de Escenarios' },
  scenarioModeActive: { en: 'Scenario', es: 'Escenario' },
  resetToDefault: { en: 'Reset to default', es: 'Restablecer valores' },
  longTermOnly: { en: 'Long-Term Only', es: 'Solo Largo Plazo' },
  ltPlusShortTerm: { en: 'LT + Short-Term', es: 'LP + Corto Plazo' },
  incomeComparison: { en: 'Income Comparison', es: 'Comparación de Ingresos' },
  longTerm: { en: 'Long-Term', es: 'Largo Plazo' },
  shortTerm: { en: 'Short-Term', es: 'Corto Plazo' },
  vsLongTerm: { en: 'vs Long-Term', es: 'vs Largo Plazo' },
  year: { en: 'year', es: 'año' },
  totalExpenses: { en: 'Total Expenses', es: 'Gastos Totales' },
  grossAnnualRent: { en: 'Gross Annual Rent', es: 'Renta Bruta Anual' },
  grossYield: { en: 'Gross Yield', es: 'Rendimiento Bruto' },
  netYieldAfterCharges: { en: 'Net Yield (after charges)', es: 'Rendimiento Neto (después de cargos)' },
  basedOnPropertyValueAtHandover: { en: 'Based on property value at handover', es: 'Basado en valor de propiedad en entrega' },
  basedOnPurchasePrice: { en: 'Based on purchase price', es: 'Basado en precio de compra' },
  
  // Section Headers
  exitStrategyAnalysis: { en: 'Exit Strategy Analysis', es: 'Análisis de Estrategia de Salida' },
  whenToSell: { en: 'When to sell for maximum returns', es: 'Cuándo vender para máximos retornos' },
  holdStrategyAnalysis: { en: 'Hold Strategy Analysis', es: 'Análisis de Estrategia de Retención' },
  holdStrategySubtitle: { en: 'Long-term rental projections and wealth accumulation', es: 'Proyecciones de renta a largo plazo y acumulación de riqueza' },
  longTermHoldAnalysis: { en: 'Long-Term Hold Analysis', es: 'Análisis de Retención a Largo Plazo' },
  tenYearProjection: { en: '10-year rental income projection', es: 'Proyección de ingresos por renta a 10 años' },
  
  // Cumulative Chart
  cumulativeNetIncome: { en: 'Cumulative Net Income', es: 'Ingreso Neto Acumulado' },
  underConstruction: { en: 'Under Construction', es: 'En Construcción' },
  breakEven: { en: 'Break-Even', es: 'Punto de Equilibrio' },
  
  // OI Growth Curve
  priceAppreciationOverTime: { en: 'Price Appreciation Over Time', es: 'Apreciación de Precio en el Tiempo' },
  exitValueAtDifferentTimePoints: { en: 'Exit value at different time points', es: 'Valor de salida en diferentes momentos' },
  monthsFromBooking: { en: 'Months from Booking', es: 'Meses desde Reserva' },
  
  // Yield & Income
  yieldAndIncome: { en: 'Yield & Income', es: 'Rendimiento e Ingresos' },
  operatingExpenses: { en: 'Operating Expenses', es: 'Gastos Operativos' },
  
  // Wealth Summary
  wealthCreated10Years: { en: 'Wealth Created (10 Years)', es: 'Riqueza Generada (10 Años)' },
  propertyValueYear10: { en: 'Property Value (Y10)', es: 'Valor de Propiedad (A10)' },
  estMarketValue: { en: 'Est. Market Value (Y10)', es: 'Valor de Mercado Est. (A10)' },
  cumulativeRentLT: { en: 'Cumulative Rent (LT)', es: 'Renta Acumulada (LP)' },
  cumulativeRentShortTerm: { en: 'Cumulative Rent (ST)', es: 'Renta Acumulada (CP)' },
  initialInvestment: { en: 'Initial Investment', es: 'Inversión Inicial' },
  netWealthLT: { en: 'Net Wealth (Long-Term)', es: 'Riqueza Neta (Largo Plazo)' },
  netWealthShortTerm: { en: 'Net Wealth (Short-Term)', es: 'Riqueza Neta (Corto Plazo)' },
  tooltipEstMarketValue: { en: 'Projected property value based on market appreciation estimates. Actual value may vary.', es: 'Valor proyectado de la propiedad basado en estimaciones de apreciación de mercado. El valor real puede variar.' },
  tooltipUnrealizedProfit: { en: 'Unrealized paper profit based on market projections. Actual returns depend on sale price at exit.', es: 'Ganancia no realizada en papel basada en proyecciones de mercado. Los retornos reales dependen del precio de venta.' },
  
  // Visibility Controls
  share: { en: 'Share', es: 'Compartir' },
  customizeClientView: { en: 'Customize Client View', es: 'Personalizar Vista del Cliente' },
  selectSectionsToShow: { en: 'Select which sections to show in the shared link', es: 'Selecciona qué secciones mostrar en el enlace compartido' },
  generateLink: { en: 'Generate Link', es: 'Generar Enlace' },
  linkCopied: { en: 'Link copied to clipboard!', es: '¡Enlace copiado al portapapeles!' },
  exportPDF: { en: 'Export PDF', es: 'Exportar PDF' },
  pdfExported: { en: 'PDF generated successfully!', es: '¡PDF generado con éxito!' },
  paymentBreakdown: { en: 'Payment Breakdown', es: 'Desglose de Pagos' },
  quotes: { en: 'Quotes', es: 'Cotizaciones' },
  viewAllQuotes: { en: 'View All Quotes', es: 'Ver Todas las Cotizaciones' },
  profileSettings: { en: 'Profile Settings', es: 'Configuración de Perfil' },
  settings: { en: 'Settings', es: 'Configuración' },
  
  // New translations for Load Quote, Language/Currency, Contact
  loadQuote: { en: 'Load Quote', es: 'Cargar Cotización' },
  selectQuote: { en: 'Select a quote to load', es: 'Selecciona una cotización para cargar' },
  noQuotesFound: { en: 'No quotes found', es: 'No se encontraron cotizaciones' },
  draft: { en: 'Draft', es: 'Borrador' },
  currency: { en: 'Currency', es: 'Moneda' },
  language: { en: 'Language', es: 'Idioma' },
  emailAdvisor: { en: 'Email Advisor', es: 'Enviar Correo' },
  messageOnWhatsApp: { en: 'Message on WhatsApp', es: 'Mensaje por WhatsApp' },
  businessEmail: { en: 'Business Email', es: 'Correo Empresarial' },
  whatsappNumber: { en: 'WhatsApp Number', es: 'Número de WhatsApp' },
  
  // Account Settings
  fullName: { en: 'Full Name', es: 'Nombre Completo' },
  saveChanges: { en: 'Save Changes', es: 'Guardar Cambios' },
  signOut: { en: 'Sign Out', es: 'Cerrar Sesión' },
  
  // Pro-rata month indicator
  months: { en: 'months', es: 'meses' },
  mo: { en: 'mo', es: 'mes' },
  
  // Payment Breakdown Section
  paymentBreakdownTitle: { en: 'Payment Breakdown', es: 'Desglose de Pagos' },
  entry: { en: 'Entry', es: 'Entrada' },
  journey: { en: 'Journey', es: 'Camino' },
  completion: { en: 'Completion', es: 'Entrega' },
  atBooking: { en: 'At Booking', es: 'En Reserva' },
  restOfDownpayment: { en: 'Rest of Downpayment', es: 'Resto de Enganche' },
  dldFeePercent: { en: 'DLD Fee (4%)', es: 'Tarifa DLD (4%)' },
  totalToday: { en: 'Total Today', es: 'Total Hoy' },
  duringConstruction: { en: 'During Construction', es: 'Durante Construcción' },
  constructionPercent: { en: 'const.', es: 'const.' },
  month: { en: 'Month', es: 'Mes' },
  subtotalInstallments: { en: 'Subtotal Installments', es: 'Subtotal Cuotas' },
  plusInstallments: { en: '+ Installments', es: '+ Cuotas' },
  totalPreHandover: { en: 'Total Pre-Handover', es: 'Total Pre-Entrega' },
  atHandoverLabel: { en: 'At Handover', es: 'En Entrega' },
  finalPayment: { en: 'Final Payment', es: 'Pago Final' },
  propertyPayments: { en: 'Property Payments', es: 'Pagos de Propiedad' },
  entryCostsDldOqood: { en: 'Entry Costs (DLD + Oqood)', es: 'Costos de Entrada (DLD + Oqood)' },
  totalToDisburse: { en: 'Total to Disburse', es: 'Total a Desembolsar' },
  
  // Payment Breakdown - Section Headers (PROPER NAMES)
  theEntry: { en: 'The Entry', es: 'La Entrada' },
  theJourney: { en: 'The Journey', es: 'El Camino' },
  completionHandover: { en: 'Completion & Handover', es: 'Entrega Final' },
  
  // Payment Summary Cards
  initialCashRequired: { en: 'Initial Cash Required', es: 'Efectivo Inicial Requerido' },
  monthlyBurnRate: { en: 'Monthly Burn Rate', es: 'Gasto Mensual' },
  completionBalance: { en: 'Completion Balance', es: 'Saldo de Entrega' },
  dueBy: { en: 'Due by', es: 'Vence' },
  
  // Timeline Legend
  booking: { en: 'Booking', es: 'Reserva' },
  milestone: { en: 'Milestone', es: 'Hito' },
  govtFee: { en: 'Govt', es: 'Gob.' },
  adminFee: { en: 'Admin', es: 'Admin' },
  
  // Government Fees
  dldRegistrationFee: { en: 'DLD Registration Fee (4%)', es: 'Tarifa Registro DLD (4%)' },
  totalCashNow: { en: 'Total Cash Required Now', es: 'Efectivo Total Requerido Ahora' },
  
  // Client Split
  ownershipStructure: { en: 'Ownership Structure', es: 'Estructura de Propiedad' },
  viewBreakdown: { en: 'View Breakdown', es: 'Ver Desglose' },
  
  // Investment Schedule Header
  investmentSchedule: { en: 'Investment Schedule', es: 'Cronograma de Inversión' },
  paymentTimeline: { en: 'Payment Timeline', es: 'Cronograma de Pagos' },
  avgMonthly: { en: 'Avg. Monthly', es: 'Promedio Mensual' },
  
  // OI Yearly Projection Table
  tenYearHoldSimulation: { en: '10-Year Hold Simulation', es: 'Simulación de Retención a 10 Años' },
  propertyValueRentalYield: { en: 'Property value, rental income & yield compression', es: 'Valor de propiedad, ingresos por renta y compresión de rendimiento' },
  yearColumn: { en: 'Year', es: 'Año' },
  phase: { en: 'Phase', es: 'Fase' },
  value: { en: 'Value', es: 'Valor' },
  netRent: { en: 'Net Rent', es: 'Renta Neta' },
  shortTermNet: { en: 'Short-Term Net', es: 'Neto Corto Plazo' },
  status: { en: 'Status', es: 'Estado' },
  difference: { en: 'Difference', es: 'Diferencia' },
  shortTermPremium: { en: 'Short-Term Premium', es: 'Prima Corto Plazo' },
  longTermAdvantage: { en: 'Long-Term Advantage', es: 'Ventaja Largo Plazo' },
  longTermTenYear: { en: 'Long-Term (10Y)', es: 'Largo Plazo (10A)' },
  shortTermTenYear: { en: 'Short-Term (10Y)', es: 'Corto Plazo (10A)' },
  build: { en: 'Build', es: 'Construcción' },
  handover: { en: 'Handover', es: 'Entrega' },
  growth: { en: 'Growth', es: 'Crecimiento' },
  mature: { en: 'Mature', es: 'Maduro' },
  totalNetIncome10Y: { en: 'Total Net Income (10Y)', es: 'Ingreso Neto Total (10A)' },
  ltLabel: { en: 'LT:', es: 'LP:' },
  stLabel: { en: 'ST:', es: 'CP:' },
  
  // Exit Scenarios Cards
  exitScenarios: { en: 'Exit Scenarios', es: 'Escenarios de Salida' },
  scenario: { en: 'scenario', es: 'escenario' },
  scenarios: { en: 'scenarios', es: 'escenarios' },
  clickToEdit: { en: 'Click to edit', es: 'Clic para editar' },
  addExit: { en: 'Add Exit', es: 'Agregar Salida' },
  exitNumber: { en: 'Exit #', es: 'Salida #' },
  construction: { en: 'construction', es: 'construcción' },
  exitAfter: { en: 'Exit after:', es: 'Salir después de:' },
  original: { en: 'Original', es: 'Original' },
  payments: { en: 'Payments', es: 'Pagos' },
  plusEntryCosts: { en: '+ Entry Costs', es: '+ Costos de Entrada' },
  totalCapitalEquals: { en: '= Total Capital', es: '= Capital Total' },
  exitPrice: { en: 'Exit Price', es: 'Precio de Salida' },
  roe: { en: 'ROE', es: 'ROE' },
  annualized: { en: 'annualized', es: 'anualizado' },
  
  // Error messages
  quoteNotFound: { en: 'Quote Not Found', es: 'Cotización No Encontrada' },
  quoteNotFoundDesc: { en: 'This quote may have been deleted or the link is invalid.', es: 'Esta cotización puede haber sido eliminada o el enlace es inválido.' },
  invalidShareLink: { en: 'Invalid share link', es: 'Enlace compartido inválido' },
  quoteDeletedOrNotFound: { en: 'Quote not found or has been deleted', es: 'Cotización no encontrada o fue eliminada' },
  
  // Disclaimer
  disclaimerText: { en: 'This cashflow statement is for informational purposes only and does not constitute financial advice.', es: 'Este estado de flujo de efectivo es solo para fines informativos y no constituye asesoramiento financiero.' },
  
  // Payment Split By Person
  paymentSplitByPerson: { en: 'Payment Split by Person', es: 'División de Pagos por Persona' },
  individualContributionBreakdown: { en: 'Individual contribution breakdown', es: 'Desglose de contribución individual' },
  shareLabel: { en: 'share', es: 'participación' },
  totalContribution: { en: 'Total contribution', es: 'Contribución total' },
  todayTotal: { en: 'Today Total', es: 'Total Hoy' },
  installmentsTotal: { en: 'Installments Total', es: 'Total Cuotas' },
  dldFee: { en: 'DLD Fee', es: 'Tarifa DLD' },
  atBookingLabel: { en: 'At Booking', es: 'En Reserva' },
  atHandoverUpper: { en: 'AT HANDOVER', es: 'EN ENTREGA' },
  duringConstructionLabel: { en: 'During Construction', es: 'Durante Construcción' },
  totalContributionUpper: { en: 'TOTAL CONTRIBUTION', es: 'CONTRIBUCIÓN TOTAL' },
  preHandoverTotal: { en: 'PRE-HANDOVER TOTAL', es: 'TOTAL PRE-ENTREGA' },
  amountNeededToResell: { en: 'Amount needed to resell', es: 'Monto para revender' },
  
  // Tooltip translations - Property & Dates
  tooltipBasePrice: { en: 'The purchase price before any fees or additional costs', es: 'El precio de compra antes de tarifas o costos adicionales' },
  tooltipBookingDate: { en: 'When you sign the SPA and make initial payments', es: 'Cuando firma el SPA y realiza los pagos iniciales' },
  tooltipHandoverDate: { en: 'Estimated date when keys are delivered and property is ready', es: 'Fecha estimada cuando se entregan las llaves' },
  
  // Tooltip translations - Entry Costs
  tooltipEoiFee: { en: 'Expression of Interest - refundable deposit deducted from downpayment', es: 'Expresión de Interés - depósito reembolsable descontado del enganche' },
  tooltipDldFee: { en: 'Dubai Land Department transfer fee - fixed at 4% of property price', es: 'Tarifa del Departamento de Tierras de Dubai - fija al 4% del precio' },
  tooltipOqoodFee: { en: 'Registration fee for off-plan properties in RERA', es: 'Tarifa de registro para propiedades en planos en RERA' },
  
  // Tooltip translations - Payment Plan
  tooltipPreHandover: { en: 'Total percentage to be paid before receiving keys', es: 'Porcentaje total a pagar antes de recibir las llaves' },
  tooltipDownpayment: { en: 'Initial payment made at booking, includes EOI', es: 'Pago inicial realizado en la reserva, incluye EOI' },
  tooltipMinExitThreshold: { en: 'Minimum % of property price that must be paid before the developer allows resale', es: '% mínimo del precio que debe pagarse antes de que el desarrollador permita reventa' },
  
  // Tooltip translations - Appreciation & Zone
  tooltipZoneMaturity: { en: 'Market maturity affects growth rates. Emerging areas have higher growth potential, established areas offer stability', es: 'La madurez del mercado afecta las tasas de crecimiento. Áreas emergentes tienen mayor potencial, áreas establecidas ofrecen estabilidad' },
  tooltipConstructionAppreciation: { en: 'Annual price growth during the construction/build phase (off-plan premium)', es: 'Crecimiento anual del precio durante la construcción (prima de pre-venta)' },
  tooltipGrowthAppreciation: { en: 'Annual appreciation rate during the initial years after handover', es: 'Tasa de apreciación anual durante los primeros años después de la entrega' },
  tooltipMatureAppreciation: { en: 'Long-term stable appreciation rate once the area is fully developed', es: 'Tasa de apreciación estable a largo plazo cuando el área está desarrollada' },
  tooltipGrowthYears: { en: 'Number of years the area continues high growth after handover before stabilizing', es: 'Número de años de alto crecimiento después de la entrega antes de estabilizarse' },
  
  // Tooltip translations - Rental Settings
  tooltipRentalYield: { en: 'Annual rental income as a percentage of property value (net after vacancy)', es: 'Ingreso anual por renta como porcentaje del valor de la propiedad (neto)' },
  tooltipServiceCharge: { en: 'Annual maintenance and management fee charged per square foot', es: 'Tarifa anual de mantenimiento por pie cuadrado' },
  tooltipRentGrowth: { en: 'Expected annual increase in long-term rental rates', es: 'Aumento anual esperado en tarifas de renta a largo plazo' },
  tooltipAdrGrowth: { en: 'Expected annual increase in short-term rental average daily rate', es: 'Aumento anual esperado en tarifa diaria promedio de renta corto plazo' },
  
  // Tooltip translations - Exit Scenarios
  tooltipRoe: { en: 'Return on Equity = Profit ÷ Total Capital Deployed. Shows efficiency of your invested money', es: 'Retorno sobre Capital = Ganancia ÷ Capital Total. Muestra eficiencia de tu inversión' },
  tooltipExitPrice: { en: 'Property value at exit, calculated using phased appreciation rates based on zone maturity', es: 'Valor de la propiedad al salir, calculado usando tasas de apreciación por fases' },
  tooltipEntryCosts: { en: 'Total upfront costs: EOI + DLD (4%) + OQOOD + any other transaction fees', es: 'Costos totales iniciales: EOI + DLD (4%) + OQOOD + otras tarifas de transacción' },
  tooltipAnnualizedRoe: { en: 'ROE adjusted to an annual rate for fair comparison across different exit timelines', es: 'ROE ajustado a tasa anual para comparación justa entre diferentes plazos de salida' },
  tooltipTotalCapital: { en: 'Total money deployed = Property payments made + Entry costs', es: 'Dinero total desplegado = Pagos de propiedad + Costos de entrada' },
  
  // Advisor Onboarding translations
  onboardingWelcome: { en: 'Welcome to the Cashflow Generator', es: 'Bienvenido al Generador de Cashflow' },
  onboardingStep1Title: { en: 'Configure Your Property', es: 'Configura Tu Propiedad' },
  onboardingStep1Desc: { en: 'Set the base price, booking date, and expected handover date', es: 'Establece el precio base, fecha de reserva y fecha de entrega' },
  onboardingStep2Title: { en: 'Set Up Payment Plan', es: 'Configura el Plan de Pago' },
  onboardingStep2Desc: { en: 'Define downpayment, milestone payments, and handover percentage', es: 'Define enganche, pagos de hitos y porcentaje de entrega' },
  onboardingStep3Title: { en: 'Customize Appreciation', es: 'Personaliza la Apreciación' },
  onboardingStep3Desc: { en: 'Select a zone or manually set appreciation rates for each phase', es: 'Selecciona una zona o establece manualmente las tasas de apreciación' },
  onboardingStep4Title: { en: 'Explore Exit Strategies', es: 'Explora Estrategias de Salida' },
  onboardingStep4Desc: { en: 'Analyze different exit timelines and save your quote', es: 'Analiza diferentes plazos de salida y guarda tu cotización' },
  
  // Client Onboarding translations
  clientOnboardingWelcome: { en: 'Your Investment Analysis', es: 'Tu Análisis de Inversión' },
  clientOnboardingStep1Title: { en: 'Your Investment Analysis', es: 'Tu Análisis de Inversión' },
  clientOnboardingStep1Desc: { en: 'This is a personalized cashflow projection for your property investment', es: 'Esta es una proyección de flujo de caja personalizada para tu inversión inmobiliaria' },
  clientOnboardingStep2Title: { en: 'Payment Timeline', es: 'Cronograma de Pagos' },
  clientOnboardingStep2Desc: { en: 'See when and how much you will pay during construction and at handover', es: 'Ve cuándo y cuánto pagarás durante la construcción y en la entrega' },
  clientOnboardingStep3Title: { en: 'Hold & Rent Strategy', es: 'Estrategia de Retención y Renta' },
  clientOnboardingStep3Desc: { en: 'Explore rental income potential if you keep the property long-term', es: 'Explora el potencial de ingresos por renta si mantienes la propiedad a largo plazo' },
  clientOnboardingStep4Title: { en: 'Exit Opportunities', es: 'Oportunidades de Salida' },
  clientOnboardingStep4Desc: { en: 'Analyze the best time to sell and maximize your returns', es: 'Analiza el mejor momento para vender y maximiza tus retornos' },
  clientOnboardingStep5Title: { en: 'Ready to Invest?', es: '¿Listo para Invertir?' },
  clientOnboardingStep5Desc: { en: 'Contact {advisor} to discuss next steps', es: 'Contacta a {advisor} para discutir los próximos pasos' },
  
  // General onboarding/help labels
  getStarted: { en: 'Get Started', es: 'Comenzar' },
  skipOnboarding: { en: 'Skip', es: 'Omitir' },
  dontShowAgain: { en: "Don't show again", es: 'No mostrar de nuevo' },
  needHelp: { en: 'Need Help?', es: '¿Necesita Ayuda?' },
  helpResources: { en: 'Help Resources', es: 'Recursos de Ayuda' },
  quickStartGuide: { en: 'Quick Start Guide', es: 'Guía de Inicio Rápido' },
  back: { en: 'Back', es: 'Atrás' },
  next: { en: 'Next', es: 'Siguiente' },
  contactAdvisor: { en: 'Contact Advisor', es: 'Contactar Asesor' },
  showGuide: { en: 'Show Guide', es: 'Mostrar Guía' },
  
  // Client View - Additional Tooltips
  tooltipGrossRent: { en: 'Annual rental income before deducting any expenses like service charges', es: 'Ingreso anual por renta antes de descontar gastos como cargos de servicio' },
  tooltipNetRent: { en: 'Rental income after deducting service charges and maintenance costs', es: 'Ingreso por renta después de descontar cargos de servicio y mantenimiento' },
  tooltipYearsToPayOff: { en: 'Number of years of net rental income needed to recover your total investment', es: 'Años de ingreso neto por renta necesarios para recuperar tu inversión total' },
  tooltipPropertyValue10Y: { en: 'Projected property value after 10 years of appreciation', es: 'Valor proyectado de la propiedad después de 10 años de apreciación' },
  tooltipCumulativeRent: { en: 'Total net rental income accumulated over the entire holding period', es: 'Ingreso neto total por renta acumulado durante todo el período de retención' },
  tooltipNetWealth: { en: 'Property value + Total rental income - Initial investment = Your total wealth created', es: 'Valor de propiedad + Ingresos por renta - Inversión inicial = Riqueza total creada' },
  tooltipPaymentPlan: { en: 'Split between pre-handover and handover payments (e.g., 30/70 means 30% before keys, 70% at handover)', es: 'División entre pagos pre-entrega y entrega (ej., 30/70 significa 30% antes de llaves, 70% en entrega)' },
  tooltipFinalPayment: { en: 'The remaining balance due when you receive the keys to your property', es: 'El saldo restante a pagar cuando reciba las llaves de su propiedad' },
  tooltipGrossYield: { en: 'Annual rent as a percentage of property price, before expenses', es: 'Renta anual como porcentaje del precio de la propiedad, antes de gastos' },
  tooltipNetYield: { en: 'Annual rent as a percentage of property price, after deducting expenses', es: 'Renta anual como porcentaje del precio de la propiedad, después de descontar gastos' },
  tooltipConstructionPeriod: { en: 'Time from booking to receiving the keys (handover)', es: 'Tiempo desde la reserva hasta recibir las llaves (entrega)' },
  tooltipOperatingExpenses: { en: 'Covers DEWA (utilities), internet, consumables, and minor maintenance costs', es: 'Cubre DEWA (servicios), internet, consumibles y costos menores de mantenimiento' },
  tooltipManagementFee: { en: 'Standard fee for holiday home agencies handling check-in, cleaning, and guest relations', es: 'Tarifa estándar para agencias de casas vacacionales que manejan check-in, limpieza y relaciones con huéspedes' },
  tooltipOccupancyRate: { en: 'Percentage of nights booked per year. Dubai market average is 65-80% for well-managed holiday homes', es: 'Porcentaje de noches reservadas por año. El promedio de Dubai es 65-80% para casas vacacionales bien gestionadas' },
  
  // Appreciation Presets
  appreciationPresets: { en: 'Appreciation Presets', es: 'Preajustes de Apreciación' },
  loadPreset: { en: 'Load Preset', es: 'Cargar Preajuste' },
  saveAsPreset: { en: 'Save as Preset', es: 'Guardar como Preajuste' },
  presetName: { en: 'Preset Name', es: 'Nombre del Preajuste' },
  deletePreset: { en: 'Delete Preset', es: 'Eliminar Preajuste' },
  noPresets: { en: 'No saved presets', es: 'Sin preajustes guardados' },
  selectPreset: { en: 'Select a preset...', es: 'Selecciona un preajuste...' },
  
  // Mortgage Calculator
  mortgage: { en: 'Mortgage', es: 'Hipoteca' },
  mortgageCalculator: { en: 'Mortgage Calculator', es: 'Calculadora de Hipoteca' },
  mortgageBreakdown: { en: 'Mortgage Breakdown', es: 'Desglose de Hipoteca' },
  enableMortgage: { en: 'Enable Mortgage', es: 'Habilitar Hipoteca' },
  enableMortgageDesc: { en: 'Add mortgage financing to your cashflow analysis', es: 'Agregar financiamiento hipotecario a tu análisis de flujo de caja' },
  financingPercent: { en: 'Financing Percentage', es: 'Porcentaje de Financiamiento' },
  financing: { en: 'Financing', es: 'Financiamiento' },
  loanTerm: { en: 'Loan Term', es: 'Plazo del Préstamo' },
  interestRate: { en: 'Interest Rate', es: 'Tasa de Interés' },
  years: { en: 'years', es: 'años' },
  mortgageFees: { en: 'Mortgage Fees', es: 'Gastos de Hipoteca' },
  processingFee: { en: 'Processing Fee', es: 'Comisión de Procesamiento' },
  valuationFee: { en: 'Valuation Fee', es: 'Comisión de Valuación' },
  mortgageRegistration: { en: 'Mortgage Registration', es: 'Registro de Hipoteca' },
  insurance: { en: 'Insurance', es: 'Seguro' },
  lifeInsurance: { en: 'Life Insurance', es: 'Seguro de Vida' },
  propertyInsurance: { en: 'Property Insurance', es: 'Seguro de Propiedad' },
  annual: { en: 'annual', es: 'anual' },
  gapRequired: { en: 'Monthly Contribution Required', es: 'Contribución Mensual Requerida' },
  gapExplanation: { en: 'Your payment plan needs additional equity to qualify for this mortgage', es: 'Tu plan de pago necesita capital adicional para calificar para esta hipoteca' },
  gapToCover: { en: 'Contribution to Cover', es: 'Contribución a Cubrir' },
  gapAmount: { en: 'Contribution Amount', es: 'Monto de Contribución' },
  monthlyContribution: { en: 'Monthly Contribution', es: 'Contribución Mensual' },
  contributionRequired: { en: 'Monthly contribution required', es: 'Contribución mensual requerida' },
  loanSummary: { en: 'Loan Summary', es: 'Resumen del Préstamo' },
  loanAmount: { en: 'Loan Amount', es: 'Monto del Préstamo' },
  monthlyPayment: { en: 'Monthly Payment', es: 'Pago Mensual' },
  equityRequired: { en: 'Equity Required', es: 'Capital Requerido' },
  totalInterest: { en: 'Total Interest', es: 'Interés Total' },
  upfrontFees: { en: 'Upfront Fees', es: 'Gastos Iniciales' },
  total: { en: 'Total', es: 'Total' },
  totalAnnual: { en: 'Total Annual', es: 'Total Anual' },
  overTerm: { en: 'Over Term', es: 'Durante el Plazo' },
  yr: { en: 'yr', es: 'año' },
  totalCostSummary: { en: 'Total Cost Summary', es: 'Resumen de Costo Total' },
  totalLoanPayments: { en: 'Total Loan Payments', es: 'Pagos Totales del Préstamo' },
  totalInterestAndFees: { en: 'Total Interest & Fees', es: 'Total de Intereses y Gastos' },
  grandTotal: { en: 'Grand Total', es: 'Gran Total' },
  grandTotalExplanation: { en: 'Total cost including gap payment, loan payments, fees and insurance over the loan term', es: 'Costo total incluyendo pago de brecha, pagos del préstamo, gastos y seguros durante el plazo' },
  gapPayment: { en: 'Additional Payment', es: 'Pago Adicional' },
  interestAndFees: { en: 'Interest & Fees', es: 'Intereses y Gastos' },
  rentVsMortgage: { en: 'Rent vs Mortgage Coverage', es: 'Renta vs Cobertura de Hipoteca' },
  monthlyRent: { en: 'Monthly Rent', es: 'Renta Mensual' },
  netMonthlyRent: { en: 'Net Monthly Rent', es: 'Renta Mensual Neta' },
  monthlyMortgageTotal: { en: 'Monthly Mortgage (+ Insurance)', es: 'Hipoteca Mensual (+ Seguro)' },
  monthlyCashflow: { en: 'Monthly Cashflow', es: 'Flujo de Caja Mensual' },
  airbnbNetMonthly: { en: 'Airbnb Net Monthly', es: 'Airbnb Neto Mensual' },
  airbnbCashflow: { en: 'Airbnb Cashflow', es: 'Flujo de Caja Airbnb' },
  mortgageAnalysis: { en: 'Mortgage Analysis', es: 'Análisis Hipotecario' },
  mortgageAnalysisSubtitle: { en: 'Loan structure, fees, and impact on cashflow', es: 'Estructura del préstamo, gastos e impacto en flujo de caja' },
  gapPaymentRequired: { en: 'Additional Payment Required', es: 'Pago Adicional Requerido' },
  gapPaymentDesc: { en: 'Your pre-handover payments do not cover the required equity. Additional payment needed before handover.', es: 'Tus pagos pre-entrega no cubren el capital requerido. Se necesita pago adicional antes de la entrega.' },
  preHandoverPayments: { en: 'Pre-Handover Payments', es: 'Pagos Pre-Entrega' },
  gapPaymentBeforeHandover: { en: 'Additional Payment (Before Handover)', es: 'Pago Adicional (Antes de Entrega)' },
  mortgageAtHandover: { en: 'Mortgage at Handover', es: 'Hipoteca en Entrega' },
  totalBeforeHandover: { en: 'Total Before Handover', es: 'Total Antes de Entrega' },
  
  // New Mortgage Client-Focused Labels
  yourCashRequirements: { en: 'Your Cash Requirements', es: 'Sus Requisitos de Efectivo' },
  totalCashNeeded: { en: 'Total Cash Needed', es: 'Efectivo Total Requerido' },
  monthlyAfterHandover: { en: 'Monthly After Handover', es: 'Mensual Después de Entrega' },
  monthlyCommitment: { en: 'Monthly Commitment', es: 'Compromiso Mensual' },
  totalInterestPaid: { en: 'Total Interest Paid', es: 'Interés Total Pagado' },
  beforeHandover: { en: 'Before Handover', es: 'Antes de Entrega' },
  additionalPaymentRequired: { en: 'Additional Payment Required', es: 'Pago Adicional Requerido' },
  appreciationBonus: { en: 'Appreciation %', es: 'Apreciación %' },
  viewMyQuote: { en: 'View My Quote', es: 'Ver Mi Cotización' },
  
  // Enabled Sections & Visibility Presets
  enabledAnalysisSections: { en: 'Enabled Analysis Sections', es: 'Secciones de Análisis Habilitadas' },
  enabledSectionsTooltip: { en: 'Disabled sections will not appear in your view or the shared client view.', es: 'Las secciones deshabilitadas no aparecerán en tu vista ni en la vista compartida del cliente.' },
  exitStrategy: { en: 'Exit Strategy', es: 'Estrategia de Salida' },
  exitStrategyDesc: { en: 'When to sell for maximum returns', es: 'Cuándo vender para máximos retornos' },
  longTermHold: { en: 'Long-Term Hold', es: 'Retención a Largo Plazo' },
  longTermHoldDesc: { en: 'Rental projections & wealth', es: 'Proyecciones de renta y patrimonio' },
  quickPresets: { en: 'Quick Presets', es: 'Preajustes Rápidos' },
  savePreset: { en: 'Save Preset', es: 'Guardar Preajuste' },
  
  // Summary View Mode
  dataView: { en: 'Data View', es: 'Vista de Datos' },
  explanationView: { en: 'Explanation View', es: 'Vista Explicativa' },
  switchToDataView: { en: 'Switch to data view', es: 'Cambiar a vista de datos' },
  switchToExplanationView: { en: 'Switch to explanation view', es: 'Cambiar a vista explicativa' },
  
  // Airbnb in Summary
  airbnbPotential: { en: 'Airbnb Potential', es: 'Potencial Airbnb' },
  comparedToLongTerm: { en: 'compared to long-term', es: 'comparado con largo plazo' },
  moreWithAirbnb: { en: 'more with Airbnb', es: 'más con Airbnb' },
  lessWithAirbnb: { en: 'less with Airbnb', es: 'menos con Airbnb' },
  netAfterMortgage: { en: 'Net After Mortgage', es: 'Neto Después de Hipoteca' },
  cashflow: { en: 'Cashflow', es: 'Flujo de Caja' },
  included: { en: 'included', es: 'incluido' },
  covers: { en: 'Covers', es: 'Cubre' },
  ofMortgage: { en: 'of mortgage', es: 'de hipoteca' },
  
  // Coverage Breakdown Popup & Tooltips
  longTermNetRentTooltip: { en: 'Gross monthly rent minus service charges', es: 'Renta bruta mensual menos cargos de servicio' },
  airbnbNetRentTooltip: { en: 'Gross Airbnb income minus operating expenses, management fees, and service charges', es: 'Ingreso bruto de Airbnb menos gastos operativos, comisiones de gestión y cargos de servicio' },
  coverageBreakdown: { en: 'Coverage Breakdown', es: 'Desglose de Cobertura' },
  grossMonthlyRent: { en: 'Gross Monthly Rent', es: 'Renta Mensual Bruta' },
  mortgagePayment: { en: 'Mortgage Payment', es: 'Pago de Hipoteca' },
  totalMortgage: { en: 'Total Mortgage', es: 'Total Hipoteca' },
  finalCashflow: { en: 'Final Cashflow', es: 'Flujo de Caja Final' },
  mortgageCovered: { en: 'of mortgage covered', es: 'de hipoteca cubierta' },
  clickForDetails: { en: 'Click for details', es: 'Clic para detalles' },
  
  // Year Comparison
  rentGrowthImpact: { en: 'Rent Growth Impact', es: 'Impacto del Crecimiento de Renta' },
  coverage: { en: 'coverage', es: 'cobertura' },
  rentIncrease: { en: 'Rent increase', es: 'Aumento de renta' },
  over5Years: { en: 'over 5 years', es: 'en 5 años' },
  year1: { en: 'Year 1', es: 'Año 1' },
  year5: { en: 'Year 5', es: 'Año 5' },
  
  // Monthly/Annual Toggle
  monthlyShort: { en: 'Mo', es: 'Mes' },
  annualShort: { en: 'Yr', es: 'Año' },
  
  // Validation messages
  completeClientInfo: { en: 'Complete Client Information', es: 'Completa la Información del Cliente' },
  completeClientInfoDesc: { en: 'Add developer, project, unit details and unit size to continue', es: 'Agrega desarrollador, proyecto, detalles de unidad y tamaño para continuar' },
  configurePropertyFinancials: { en: 'Configure Property Financials', es: 'Configura los Datos Financieros' },
  configurePropertyFinancialsDesc: { en: 'Set the base price and payment plan to generate projections', es: 'Establece el precio base y plan de pagos para generar proyecciones' },
  
  // Version History
  versionHistory: { en: 'Version History', es: 'Historial de Versiones' },
  restore: { en: 'Restore', es: 'Restaurar' },
  latestVersion: { en: 'Latest', es: 'Última' },
  noVersions: { en: 'No previous versions', es: 'Sin versiones anteriores' },
  versionsCreatedOnSave: { en: 'Versions are created each time you save', es: 'Las versiones se crean cada vez que guardas' },
  confirmRestore: { en: 'Restore this version?', es: '¿Restaurar esta versión?' },
  confirmRestoreDesc: { en: 'This will replace the current quote with the selected version. A new version will be saved with the current state before restoring.', es: 'Esto reemplazará la cotización actual con la versión seleccionada. Se guardará una nueva versión con el estado actual antes de restaurar.' },
  cancel: { en: 'Cancel', es: 'Cancelar' },
  versionRestored: { en: 'Version restored successfully', es: 'Versión restaurada exitosamente' },
  
  // Landing Page
  landingSignIn: { en: 'Sign In', es: 'Iniciar Sesión' },
  landingGetStarted: { en: 'Get Started', es: 'Comenzar' },
  landingMenu: { en: 'Menu', es: 'Menú' },
  landingPoweredByAI: { en: 'Powered by AI Intelligence', es: 'Impulsado por Inteligencia Artificial' },
  landingHeroTitle1: { en: 'The Future of', es: 'El Futuro de la' },
  landingHeroTitle2: { en: 'Real Estate Investment', es: 'Inversión Inmobiliaria' },
  landingHeroTitle3: { en: 'in Dubai', es: 'en Dubai' },
  landingHeroDescription: { 
    en: 'Next-generation investment analysis tools. Interactive maps, AI-powered ROI calculators, and professional cashflow generator — all in one platform.', 
    es: 'Herramientas de análisis de inversión de próxima generación. Mapas interactivos, calculadoras ROI con IA, y generador de cashflow profesional — todo en una plataforma.' 
  },
  landingAccessPlatform: { en: 'Access Platform', es: 'Acceder a la Plataforma' },
  landingViewDemo: { en: 'View Demo', es: 'Ver Demo' },
  landingProjectsMapped: { en: 'Projects Mapped', es: 'Proyectos Mapeados' },
  landingInvestmentZones: { en: 'Investment Zones', es: 'Zonas de Inversión' },
  landingSmartAnalysis: { en: 'Smart Analysis', es: 'Análisis Inteligente' },
  landingProfessionalTools: { en: 'Professional Tools', es: 'Herramientas Profesionales' },
  landingProfessionalToolsDesc: { en: 'Everything you need to make informed investment decisions in Dubai real estate market', es: 'Todo lo que necesitas para tomar decisiones de inversión informadas en el mercado inmobiliario de Dubai' },
  landingInteractiveMap: { en: 'Interactive Map', es: 'Mapa Interactivo' },
  landingInteractiveMapDesc: { 
    en: 'Explore investment zones, off-plan projects, landmarks and hotspots in real-time with smart data layers.', 
    es: 'Explora zonas de inversión, proyectos off-plan, landmarks y hotspots en tiempo real con capas de datos inteligentes.' 
  },
  landingExploreMap: { en: 'Explore Map', es: 'Explorar Mapa' },
  landingRoiCalculator: { en: 'ROI Calculator', es: 'Calculadora ROI' },
  landingRoiCalculatorDesc: { 
    en: 'Compare OI, SI and HO investment profiles with precise projections and detailed exit scenarios.', 
    es: 'Compara perfiles de inversión OI, SI y HO con proyecciones precisas y escenarios de salida detallados.' 
  },
  landingCalculateRoi: { en: 'Calculate ROI', es: 'Calcular ROI' },
  landingCashflowGenerator: { en: 'Cashflow Generator', es: 'Generador de Cashflow' },
  landingCashflowGeneratorDesc: { 
    en: 'Create professional reports with payment breakdowns and custom quotes for your clients.', 
    es: 'Crea reportes profesionales con desglose de pagos y cotizaciones personalizadas para tus clientes.' 
  },
  landingCreateQuote: { en: 'Create Quote', es: 'Crear Cotización' },
  landingProjectedRoi: { en: 'Projected ROI', es: 'ROI Proyectado' },
  landingAnnualYield: { en: 'Annual Yield', es: 'Yield Anual' },
  landingAccuracy: { en: 'Accuracy', es: 'Precisión' },
  landingCtaTitle: { en: 'Ready to Transform Your Investment Strategy?', es: '¿Listo para Transformar tu Estrategia de Inversión?' },
  landingCtaDescription: { en: 'Join professionals using Dubai Invest Pro to make smarter investment decisions.', es: 'Únete a los profesionales que usan Dubai Invest Pro para tomar decisiones de inversión más inteligentes.' },
  landingCtaButton: { en: 'Start Now — It\'s Free', es: 'Comenzar Ahora — Es Gratis' },
  landingRightsReserved: { en: 'All rights reserved.', es: 'Todos los derechos reservados.' },
  landingPrivacy: { en: 'Privacy', es: 'Privacidad' },
  landingTerms: { en: 'Terms', es: 'Términos' },
  landingContact: { en: 'Contact', es: 'Contacto' },
  
  // Login Page
  loginTitle: { en: 'Dubai Investment Hub', es: 'Dubai Investment Hub' },
  loginSubtitle: { en: 'Advisory Platform', es: 'Plataforma de Asesoría' },
  loginSignIn: { en: 'Sign in', es: 'Iniciar sesión' },
  loginSignUp: { en: 'Sign up', es: 'Registrarse' },
  
  // Home Page
  homeWelcome: { en: 'Welcome', es: 'Bienvenido' },
  homeSubtitle: { en: 'Your investment advisory dashboard', es: 'Tu panel de asesoría de inversiones' },
  homeInvestorType: { en: 'Investor Type', es: 'Tipo de Inversionista' },
  homeInvestorTypeDesc: { en: 'Compare OI, SI, HO investment profiles and analyze returns', es: 'Compara perfiles de inversión OI, SI, HO y analiza retornos' },
  homeCashflowGenerator: { en: 'Cashflow Generator', es: 'Generador de Cashflow' },
  homeCashflowGeneratorDesc: { en: 'Exit scenarios, payment breakdowns & client quotes', es: 'Escenarios de salida, desglose de pagos y cotizaciones' },
  homeInvestmentMap: { en: 'Investment Map', es: 'Mapa de Inversión' },
  homeInvestmentMapDesc: { en: 'Dubai zones, projects, hotspots & live presentations', es: 'Zonas de Dubai, proyectos, hotspots y presentaciones en vivo' },
  homeMyGenerators: { en: 'My Generators', es: 'Mis Generadores' },
  allOpportunities: { en: 'All Opportunities', es: 'Todas las Oportunidades' },
  homeConfiguration: { en: 'Configuration', es: 'Configuración' },
  homeAccountSettings: { en: 'Account Settings', es: 'Configuración de Cuenta' },
  yourData: { en: 'Your Data', es: 'Tus Datos' },
  dealClosed: { en: 'Deal closed! Congratulations!', es: '¡Trato cerrado! ¡Felicitaciones!' },
  homeRecentGenerators: { en: 'Recent Cashflow Generators', es: 'Generadores de Cashflow Recientes' },
  homeViewAll: { en: 'View All', es: 'Ver Todos' },
  homeUnnamedClient: { en: 'Unnamed Client', es: 'Cliente sin Nombre' },
  homeNoProject: { en: 'No project', es: 'Sin proyecto' },
  
  // Investment Overview Grid
  investmentOverview: { en: 'Investment Overview', es: 'Resumen de Inversión' },
  overviewCashToStart: { en: 'Cash to Start', es: 'Efectivo Inicial' },
  includesDownpaymentFees: { en: 'Includes downpayment + DLD + fees', es: 'Incluye anticipo + DLD + tarifas' },
  cash: { en: 'Cash', es: 'Efectivo' },
  financed: { en: 'Financed', es: 'Financiado' },
  nextMilestone: { en: 'Next milestone', es: 'Próximo hito' },
  overviewMonthlyPerformance: { en: 'Monthly Performance', es: 'Rendimiento Mensual' },
  rentIncome: { en: 'Rent Income', es: 'Ingreso Alquiler' },
  mortgageCost: { en: 'Mortgage Cost', es: 'Costo Hipoteca' },
  selfFunding: { en: 'Self-Funding', es: 'Auto-Financiado' },
  monthlyGap: { en: 'Monthly Gap', es: 'Brecha Mensual' },
  propertyPaysItself: { en: 'Property pays for itself', es: 'La propiedad se paga sola' },
  monthlyContributionNeeded: { en: 'Monthly contribution needed', es: 'Se necesita aporte mensual' },
  overviewProjectedProfit: { en: 'Projected Net Profit', es: 'Ganancia Neta Proyectada' },
  recommendedExit: { en: 'Recommended Exit', es: 'Salida Recomendada' },
  profitFromSale: { en: 'Profit from Sale', es: 'Ganancia por Venta' },
  profitFromRent: { en: 'Profit from Rent', es: 'Ganancia por Alquiler' },
  overviewBreakeven: { en: 'Time to Breakeven', es: 'Tiempo de Recuperación' },
  marketAvg: { en: 'Market Avg', es: 'Promedio Mercado' },
  overviewNetYield: { en: 'Net Yield', es: 'Rendimiento Neto' },
  fasterThanMarket: { en: 'Faster than market average', es: 'Más rápido que el promedio' },
  
  // Account Settings Page
  accountSettingsTitle: { en: 'Account Settings', es: 'Configuración de Cuenta' },
  accountEmail: { en: 'Email', es: 'Correo Electrónico' },
  accountEmailCannotChange: { en: 'Email cannot be changed', es: 'El correo no puede ser cambiado' },
  accountFullName: { en: 'Full Name', es: 'Nombre Completo' },
  accountEnterFullName: { en: 'Enter your full name', es: 'Ingresa tu nombre completo' },
  accountBusinessEmail: { en: 'Business Email', es: 'Correo Empresarial' },
  accountBusinessEmailDesc: { en: 'Clients can contact you via this email', es: 'Los clientes pueden contactarte por este correo' },
  accountWhatsApp: { en: 'WhatsApp Number', es: 'Número de WhatsApp' },
  accountWhatsAppDesc: { en: 'Clients can message you on WhatsApp', es: 'Los clientes pueden enviarte mensajes por WhatsApp' },
  accountClickToUpload: { en: 'Click camera to upload photo', es: 'Clic en cámara para subir foto' },
  accountSaving: { en: 'Saving...', es: 'Guardando...' },
  accountSaveChanges: { en: 'Save Changes', es: 'Guardar Cambios' },
  accountViewGenerators: { en: 'View My Cashflow Generators', es: 'Ver Mis Generadores de Cashflow' },
  accountAdminDashboard: { en: 'Admin Dashboard', es: 'Panel de Administración' },
  themePreference: { en: 'Theme Preference', es: 'Preferencia de Tema' },
  themePreferenceDesc: { en: 'Choose how the application looks. This will be saved to your profile.', es: 'Elige cómo se ve la aplicación. Esto se guardará en tu perfil.' },
  
  // Quotes Dashboard Page
  quotesTitle: { en: 'My Cashflow Generators', es: 'Mis Generadores de Cashflow' },
  quotesSaved: { en: 'quotes saved', es: 'cotizaciones guardadas' },
  quotesNewQuote: { en: 'New Quote', es: 'Nueva Cotización' },
  quotesNoQuotes: { en: 'No quotes yet', es: 'Sin cotizaciones aún' },
  quotesNoQuotesDesc: { en: 'Create your first cashflow generator to get started', es: 'Crea tu primer generador de cashflow para comenzar' },
  quotesCreateQuote: { en: 'Create Quote', es: 'Crear Cotización' },
  quotesUntitled: { en: 'Untitled Quote', es: 'Cotización Sin Título' },
  quotesClient: { en: 'Client', es: 'Cliente' },
  quotesProject: { en: 'Project', es: 'Proyecto' },
  quotesDeveloper: { en: 'Developer', es: 'Desarrollador' },
  quotesDeleteTitle: { en: 'Delete Quote', es: 'Eliminar Cotización' },
  quotesDeleteDesc: { en: 'Are you sure you want to delete "{title}"? This action cannot be undone.', es: '¿Estás seguro de que deseas eliminar "{title}"? Esta acción no se puede deshacer.' },
  quotesCancel: { en: 'Cancel', es: 'Cancelar' },
  quotesDelete: { en: 'Delete', es: 'Eliminar' },
  
  // 404 Page
  notFound404: { en: '404', es: '404' },
  notFoundTitle: { en: 'Oops! Page not found', es: '¡Ups! Página no encontrada' },
  notFoundReturn: { en: 'Return to Home', es: 'Volver al Inicio' },
  
  // ROI Calculator Page
  roiInvestorType: { en: 'Investor Type', es: 'Tipo de Inversionista' },
  roiCompareProfiles: { en: 'Compare OI, SI, HO investment profiles', es: 'Compara perfiles de inversión OI, SI, HO' },
  roiDetailedComparison: { en: 'Detailed Comparison', es: 'Comparación Detallada' },
  roiMetric: { en: 'Metric', es: 'Métrica' },
  roiEntryPrice: { en: 'Entry Price', es: 'Precio de Entrada' },
  roiExitPrice: { en: 'Exit Price', es: 'Precio de Salida' },
  roiEquityInvested: { en: 'Equity Invested', es: 'Capital Invertido' },
  roiProjectedProfit: { en: 'Projected Profit', es: 'Ganancia Proyectada' },
  roiRentalYield: { en: 'Rental Yield', es: 'Rendimiento de Renta' },
  roiYearsToPay: { en: 'Years to Pay', es: 'Años para Recuperar' },
  
  // ROI Input Modal translations
  configureInvestment: { en: 'Configure Investment', es: 'Configurar Inversión' },
  investmentParameters: { en: 'Investment Parameters', es: 'Parámetros de Inversión' },
  oiHoldingPeriod: { en: 'OI Holding Period (months)', es: 'Período de Tenencia OI (meses)' },
  resaleThresholdOIEquity: { en: 'Resale Threshold % (OI Equity)', es: 'Umbral de Reventa % (Capital OI)' },
  appreciationRateCAGR: { en: 'Appreciation Rate (CAGR) %', es: 'Tasa de Apreciación (CAGR) %' },
  oiSellsToSI: { en: 'OI sells to SI after', es: 'OI vende a SI después de' },
  oiDeploysToResell: { en: 'OI deploys {amount} to resell', es: 'OI despliega {amount} para revender' },
  
  // Month names (short)
  monthJan: { en: 'Jan', es: 'Ene' },
  monthFeb: { en: 'Feb', es: 'Feb' },
  monthMar: { en: 'Mar', es: 'Mar' },
  monthApr: { en: 'Apr', es: 'Abr' },
  monthMay: { en: 'May', es: 'May' },
  monthJun: { en: 'Jun', es: 'Jun' },
  monthJul: { en: 'Jul', es: 'Jul' },
  monthAug: { en: 'Aug', es: 'Ago' },
  monthSep: { en: 'Sep', es: 'Sep' },
  monthOct: { en: 'Oct', es: 'Oct' },
  monthNov: { en: 'Nov', es: 'Nov' },
  monthDec: { en: 'Dec', es: 'Dic' },
  
  // OI Input Modal additional translations
  oiInvestmentParametersTitle: { en: 'OI Investment Parameters', es: 'Parámetros de Inversión OI' },
  entryCostsAtBookingLabel: { en: 'Entry Costs (At Booking)', es: 'Costos de Entrada (En Reserva)' },
  dldFeeLabelFixed: { en: 'DLD Fee (fixed)', es: 'Tarifa DLD (fija)' },
  minExitThresholdDescLabel: { en: '% of price developer requires paid before allowing resale', es: '% del precio que el developer exige haber pagado para permitir reventa' },
  preHandoverSplitLabel: { en: 'Pre-Handover / Handover Split', es: 'División Pre-Entrega / Entrega' },
  timeBasedMonthLabel: { en: 'Time-based (Month)', es: 'Basado en Tiempo (Mes)' },
  constructionBasedLabel: { en: 'Construction %', es: 'Construcción %' },
  handoverPaymentAutoLabel: { en: 'Handover Payment (Automatic)', es: 'Pago de Entrega (Automático)' },
  atHandoverDateLabel: { en: 'At handover date', es: 'En fecha de entrega' },
  monthLabelPlaceholder: { en: 'Month', es: 'Mes' },
  yearLabelPlaceholder: { en: 'Year', es: 'Año' },
  quarterLabelPlaceholder: { en: 'Quarter', es: 'Trimestre' },
  
  // Client Unit Modal translations
  splitPaymentsBetweenClients: { en: 'Split payments between clients', es: 'Dividir pagos entre clientes' },
  assignContributionPercentage: { en: 'Assign contribution percentage to each client', es: 'Asignar porcentaje de contribución a cada cliente' },
  mustEqual100: { en: 'Must equal 100%', es: 'Debe sumar 100%' },
  distributeEqually: { en: 'Distribute equally', es: 'Distribuir equitativamente' },
  totalLabel: { en: 'Total', es: 'Total' },
  
  // Cashflow Summary Card translations
  summaryTitle: { en: 'Investment Summary', es: 'Resumen de Inversión' },
  summarySubtitle: { en: 'Complete overview for client sharing', es: 'Resumen completo para compartir con el cliente' },
  copyToClipboard: { en: 'Copy', es: 'Copiar' },
  copiedToClipboard: { en: 'Copied!', es: '¡Copiado!' },
  copied: { en: 'Copied', es: 'Copiado' },
  copy: { en: 'Copy', es: 'Copiar' },
  editSummary: { en: 'Edit', es: 'Editar' },
  doneEditing: { en: 'Done', es: 'Listo' },
  resetSummary: { en: 'Reset', es: 'Restablecer' },
  edited: { en: 'Edited', es: 'Editado' },
  clickToCollapse: { en: 'Click to collapse', es: 'Clic para colapsar' },
  clickToExpand: { en: 'Click to expand', es: 'Clic para expandir' },
  
  // Summary Section Titles
  propertyOverviewSection: { en: 'Property Overview', es: 'Resumen de la Propiedad' },
  paymentStructureSection: { en: 'Payment Structure', es: 'Estructura de Pago' },
  timelineSection: { en: 'Timeline', es: 'Cronograma' },
  todaysCommitmentSection: { en: "Today's Commitment", es: 'Compromiso de Hoy' },
  duringConstructionSection: { en: 'During Construction', es: 'Durante la Construcción' },
  atHandoverSection: { en: 'At Handover', es: 'En la Entrega' },
  rentalPotentialSection: { en: 'Rental Potential', es: 'Potencial de Renta' },
  exitOptionsSection: { en: 'Exit Options', es: 'Opciones de Salida' },
  mortgageSection: { en: 'Mortgage Analysis', es: 'Análisis de Hipoteca' },
  
  // Summary Toggle Labels
  sectionsToInclude: { en: 'Sections to include:', es: 'Secciones a incluir:' },
  includeRentalAnalysis: { en: 'Include Rental Analysis', es: 'Incluir Análisis de Renta' },
  includeExitScenarios: { en: 'Include Exit Scenarios', es: 'Incluir Escenarios de Salida' },
  includeMortgageAnalysis: { en: 'Include Mortgage Analysis', es: 'Incluir Análisis de Hipoteca' },
  installmentBreakdown: { en: 'Breakdown by installment:', es: 'Desglose por cuota:' },
  
  // Summary Row Labels
  projectLabel: { en: 'Project', es: 'Proyecto' },
  preHandover: { en: 'Pre-Handover', es: 'Pre-Entrega' },
  effectiveYield: { en: 'Effective Yield', es: 'Rendimiento Efectivo' },
  noAdditionalPaymentsMsg: { en: 'No additional payments during construction', es: 'Sin pagos adicionales durante la construcción' },
  surplus: { en: 'Surplus', es: 'Excedente' },
  gap: { en: 'Gap', es: 'Diferencia' },
  
  // Dashboard Tabs
  tabProperty: { en: 'The Asset', es: 'El Activo' },
  tabPayments: { en: 'Cashflow', es: 'Flujo de Caja' },
  tabHold: { en: 'Yield & Income', es: 'Rendimiento e Ingresos' },
  tabExit: { en: 'Exit Strategy', es: 'Estrategia de Salida' },
  tabMortgage: { en: 'Leverage', es: 'Apalancamiento' },
  tabSummary: { en: 'Report', es: 'Reporte' },
  switchToClassic: { en: 'Classic View', es: 'Vista Clásica' },
  switchToDashboard: { en: 'Dashboard View', es: 'Vista Dashboard' },
  
  // Payment Timeline (unique keys to avoid duplicates)
  paymentTimelineLabel: { en: 'Payment Timeline', es: 'Cronograma de Pagos' },
  govFeeLabel: { en: 'Govt', es: 'Gob.' },
  preHandoverLabel: { en: 'Pre-Handover', es: 'Pre-Entrega' },
  atHandoverTimelineLabel: { en: 'At Handover', es: 'En Entrega' },
  payBeforeKeys: { en: 'Pay before receiving keys', es: 'Pagar antes de recibir llaves' },
  payAtCompletion: { en: 'Pay at completion', es: 'Pagar en la entrega' },
  clickPaymentForDetails: { en: 'Click on a payment for more details', es: 'Haz clic en un pago para más detalles' },
  
  // Auth - Login (additional keys)
  loginEmail: { en: 'Email', es: 'Correo electrónico' },
  loginPassword: { en: 'Password', es: 'Contraseña' },
  loginForgotPassword: { en: 'Forgot password?', es: '¿Olvidaste tu contraseña?' },
  loginSigningIn: { en: 'Signing in...', es: 'Iniciando sesión...' },
  loginWelcomeBack: { en: 'Welcome back!', es: '¡Bienvenido de nuevo!' },
  loginInvalidCredentials: { en: 'Invalid email or password', es: 'Correo o contraseña inválidos' },
  loginFailed: { en: 'Failed to login', es: 'Error al iniciar sesión' },
  
  // Auth - Signup (additional keys)
  signupFullName: { en: 'Full Name', es: 'Nombre Completo' },
  signupCreateAccount: { en: 'Create account', es: 'Crear cuenta' },
  signupCreatingAccount: { en: 'Creating account...', es: 'Creando cuenta...' },
  signupSuccess: { en: 'Account created successfully!', es: '¡Cuenta creada exitosamente!' },
  signupFailed: { en: 'Failed to create account', es: 'Error al crear cuenta' },
  signupAlreadyRegistered: { en: 'This email is already registered. Please sign in instead.', es: 'Este correo ya está registrado. Por favor inicia sesión.' },
  signupAcceptTerms: { en: 'I agree to the', es: 'Acepto los' },
  signupAnd: { en: 'and', es: 'y' },
  
  // Auth - Forgot Password
  forgotPasswordTitle: { en: 'Reset your password', es: 'Restablecer contraseña' },
  forgotPasswordDescription: { en: 'Enter your email and we\'ll send you a reset link', es: 'Ingresa tu correo y te enviaremos un enlace' },
  forgotPasswordSendLink: { en: 'Send reset link', es: 'Enviar enlace' },
  forgotPasswordSending: { en: 'Sending...', es: 'Enviando...' },
  forgotPasswordEmailSent: { en: 'Reset link sent! Check your email.', es: '¡Enlace enviado! Revisa tu correo.' },
  forgotPasswordError: { en: 'Failed to send reset link', es: 'Error al enviar enlace' },
  forgotPasswordCheckEmail: { en: 'Check your email', es: 'Revisa tu correo' },
  forgotPasswordEmailSentTo: { en: 'We sent a password reset link to', es: 'Enviamos un enlace de restablecimiento a' },
  forgotPasswordCheckSpam: { en: 'Don\'t see the email? Check your spam folder.', es: '¿No ves el correo? Revisa tu carpeta de spam.' },
  forgotPasswordBackToLogin: { en: 'Back to login', es: 'Volver al inicio de sesión' },
  
  // Auth - Reset Password
  resetPasswordTitle: { en: 'Create new password', es: 'Crear nueva contraseña' },
  resetPasswordDescription: { en: 'Enter your new password below', es: 'Ingresa tu nueva contraseña' },
  resetPasswordNewPassword: { en: 'New Password', es: 'Nueva Contraseña' },
  resetPasswordConfirm: { en: 'Confirm Password', es: 'Confirmar Contraseña' },
  resetPasswordUpdate: { en: 'Update password', es: 'Actualizar contraseña' },
  resetPasswordUpdating: { en: 'Updating...', es: 'Actualizando...' },
  resetPasswordSuccess: { en: 'Password updated successfully!', es: '¡Contraseña actualizada!' },
  resetPasswordError: { en: 'Failed to update password', es: 'Error al actualizar contraseña' },
  resetPasswordSuccessTitle: { en: 'Password updated!', es: '¡Contraseña actualizada!' },
  resetPasswordSuccessDesc: { en: 'Redirecting you to login...', es: 'Redirigiendo al inicio de sesión...' },
  resetPasswordInvalidLink: { en: 'This password reset link is invalid or has expired. Please request a new one.', es: 'Este enlace es inválido o ha expirado. Solicita uno nuevo.' },
  resetPasswordInvalidTitle: { en: 'Invalid Reset Link', es: 'Enlace Inválido' },
  resetPasswordGoToLogin: { en: 'Go to Login', es: 'Ir al Inicio de Sesión' },
  
  // Legal Pages
  landingHelp: { en: 'Help', es: 'Ayuda' },
  privacyTitle: { en: 'Privacy Policy', es: 'Política de Privacidad' },
  privacyBackToHome: { en: 'Back to Home', es: 'Volver al Inicio' },
  privacyLastUpdated: { en: 'Last updated', es: 'Última actualización' },
  privacyIntroTitle: { en: 'Introduction', es: 'Introducción' },
  privacyIntroText: { en: 'Dubai Invest Pro is committed to protecting your privacy. This policy explains how we collect, use, and safeguard your information when you use our platform.', es: 'Dubai Invest Pro está comprometido con proteger tu privacidad. Esta política explica cómo recopilamos, usamos y protegemos tu información.' },
  privacyCollectTitle: { en: 'Information We Collect', es: 'Información que Recopilamos' },
  privacyCollectAccountTitle: { en: 'Account Information', es: 'Información de Cuenta' },
  privacyCollectAccountItem1: { en: 'Email address and name when you create an account', es: 'Correo electrónico y nombre al crear una cuenta' },
  privacyCollectAccountItem2: { en: 'Profile information you choose to provide', es: 'Información de perfil que decidas proporcionar' },
  privacyCollectAccountItem3: { en: 'Authentication credentials (securely encrypted)', es: 'Credenciales de autenticación (encriptadas)' },
  privacyCollectUsageTitle: { en: 'Usage Information', es: 'Información de Uso' },
  privacyCollectUsageItem1: { en: 'Investment calculations and quotes you create', es: 'Cálculos de inversión y cotizaciones que crees' },
  privacyCollectUsageItem2: { en: 'Feature usage and preferences', es: 'Uso de funciones y preferencias' },
  privacyCollectUsageItem3: { en: 'Device and browser information for security', es: 'Información de dispositivo y navegador para seguridad' },
  privacyUseTitle: { en: 'How We Use Your Information', es: 'Cómo Usamos tu Información' },
  privacyUseItem1: { en: 'Provide and improve our investment analysis tools', es: 'Proveer y mejorar nuestras herramientas de análisis' },
  privacyUseItem2: { en: 'Save your quotes and preferences across sessions', es: 'Guardar tus cotizaciones y preferencias entre sesiones' },
  privacyUseItem3: { en: 'Send important account and security notifications', es: 'Enviar notificaciones importantes de cuenta y seguridad' },
  privacyUseItem4: { en: 'Analyze usage patterns to enhance features', es: 'Analizar patrones de uso para mejorar funciones' },
  privacyUseItem5: { en: 'Comply with legal obligations', es: 'Cumplir con obligaciones legales' },
  privacySecurityTitle: { en: 'Data Storage & Security', es: 'Almacenamiento y Seguridad' },
  privacySecurityText: { en: 'We implement industry-standard security measures including encryption, secure data storage, and regular security audits. Your data is stored on secure cloud infrastructure with access controls and monitoring.', es: 'Implementamos medidas de seguridad estándar de la industria incluyendo encriptación, almacenamiento seguro y auditorías regulares.' },
  privacyRightsTitle: { en: 'Your Rights', es: 'Tus Derechos' },
  privacyRightsItem1: { en: 'Access and download your personal data', es: 'Acceder y descargar tus datos personales' },
  privacyRightsItem2: { en: 'Request correction of inaccurate information', es: 'Solicitar corrección de información incorrecta' },
  privacyRightsItem3: { en: 'Request deletion of your account and data', es: 'Solicitar eliminación de tu cuenta y datos' },
  privacyRightsItem4: { en: 'Opt out of marketing communications', es: 'Cancelar comunicaciones de marketing' },
  privacyContactTitle: { en: 'Contact Us', es: 'Contáctanos' },
  privacyContactText: { en: 'If you have questions about this privacy policy or your data, please', es: 'Si tienes preguntas sobre esta política o tus datos, por favor' },
  privacyContactLink: { en: 'contact us', es: 'contáctanos' },
  
  // Terms of Service
  termsTitle: { en: 'Terms of Service', es: 'Términos de Servicio' },
  termsBackToHome: { en: 'Back to Home', es: 'Volver al Inicio' },
  termsLastUpdated: { en: 'Last updated', es: 'Última actualización' },
  termsAcceptanceTitle: { en: 'Acceptance of Terms', es: 'Aceptación de Términos' },
  termsAcceptanceText: { en: 'By accessing or using Dubai Invest Pro, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.', es: 'Al acceder o usar Dubai Invest Pro, aceptas estos Términos de Servicio. Si no estás de acuerdo, por favor no uses nuestro servicio.' },
  termsServiceTitle: { en: 'Description of Service', es: 'Descripción del Servicio' },
  termsServiceText: { en: 'Dubai Invest Pro provides real estate investment analysis tools including:', es: 'Dubai Invest Pro proporciona herramientas de análisis de inversión inmobiliaria incluyendo:' },
  termsServiceItem1: { en: 'ROI and cashflow calculators', es: 'Calculadoras de ROI y flujo de caja' },
  termsServiceItem2: { en: 'Interactive property maps', es: 'Mapas interactivos de propiedades' },
  termsServiceItem3: { en: 'Quote generation and sharing', es: 'Generación y compartir cotizaciones' },
  termsServiceItem4: { en: 'Developer and zone information', es: 'Información de desarrolladores y zonas' },
  termsUserTitle: { en: 'User Responsibilities', es: 'Responsabilidades del Usuario' },
  termsUserItem1: { en: 'Provide accurate information when creating an account', es: 'Proporcionar información precisa al crear una cuenta' },
  termsUserItem2: { en: 'Maintain the security of your account credentials', es: 'Mantener la seguridad de tus credenciales' },
  termsUserItem3: { en: 'Use the service only for lawful purposes', es: 'Usar el servicio solo para propósitos legales' },
  termsUserItem4: { en: 'Not attempt to interfere with the service operation', es: 'No intentar interferir con la operación del servicio' },
  termsIPTitle: { en: 'Intellectual Property', es: 'Propiedad Intelectual' },
  termsIPText: { en: 'All content, features, and functionality of Dubai Invest Pro are owned by us and are protected by international copyright, trademark, and other intellectual property laws.', es: 'Todo el contenido, funciones y funcionalidad de Dubai Invest Pro son de nuestra propiedad y están protegidos por leyes internacionales de propiedad intelectual.' },
  termsDisclaimerTitle: { en: 'Investment Disclaimer', es: 'Descargo de Inversión' },
  termsDisclaimerText: { en: 'The calculations, projections, and information provided are for informational purposes only and do not constitute financial, investment, or legal advice. Past performance does not guarantee future results. Always consult with qualified professionals before making investment decisions.', es: 'Los cálculos, proyecciones e información proporcionada son solo para fines informativos y no constituyen asesoramiento financiero, de inversión o legal. El rendimiento pasado no garantiza resultados futuros.' },
  termsLiabilityTitle: { en: 'Limitation of Liability', es: 'Limitación de Responsabilidad' },
  termsLiabilityText: { en: 'Dubai Invest Pro shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service or any investment decisions made based on information provided.', es: 'Dubai Invest Pro no será responsable por daños indirectos, incidentales, especiales, consecuentes o punitivos resultantes del uso del servicio o decisiones de inversión basadas en la información proporcionada.' },
  termsTerminationTitle: { en: 'Termination', es: 'Terminación' },
  termsTerminationText: { en: 'We reserve the right to suspend or terminate your access to the service at any time, with or without cause, and with or without notice.', es: 'Nos reservamos el derecho de suspender o terminar tu acceso al servicio en cualquier momento, con o sin causa, y con o sin aviso previo.' },
  termsGoverningTitle: { en: 'Governing Law', es: 'Ley Aplicable' },
  termsGoverningText: { en: 'These terms shall be governed by and construed in accordance with the laws of the United Arab Emirates, without regard to its conflict of law provisions.', es: 'Estos términos se regirán e interpretarán de acuerdo con las leyes de los Emiratos Árabes Unidos, sin tener en cuenta sus disposiciones de conflicto de leyes.' },
  
  // Contact Page
  contactTitle: { en: 'Contact Us', es: 'Contáctanos' },
  contactGetInTouch: { en: 'Get in Touch', es: 'Ponte en Contacto' },
  contactDescription: { en: 'Have questions about our platform? We\'re here to help.', es: '¿Tienes preguntas sobre nuestra plataforma? Estamos aquí para ayudar.' },
  contactEmailTitle: { en: 'Email', es: 'Correo Electrónico' },
  contactEmailText: { en: 'For general inquiries and support', es: 'Para consultas generales y soporte' },
  contactWhatsAppTitle: { en: 'WhatsApp', es: 'WhatsApp' },
  contactWhatsAppText: { en: 'Quick responses during business hours', es: 'Respuestas rápidas en horario laboral' },
  contactResponseTime: { en: 'Response Time', es: 'Tiempo de Respuesta' },
  contactResponseTimeText: { en: 'We typically respond within 24 hours during business days.', es: 'Normalmente respondemos dentro de 24 horas en días hábiles.' },
  contactFormName: { en: 'Your Name', es: 'Tu Nombre' },
  contactFormNamePlaceholder: { en: 'John Doe', es: 'Juan Pérez' },
  contactFormEmail: { en: 'Email Address', es: 'Correo Electrónico' },
  contactFormEmailPlaceholder: { en: 'you@example.com', es: 'tu@ejemplo.com' },
  contactFormSubject: { en: 'Subject', es: 'Asunto' },
  contactFormSubjectPlaceholder: { en: 'How can we help?', es: '¿Cómo podemos ayudarte?' },
  contactFormMessage: { en: 'Message', es: 'Mensaje' },
  contactFormMessagePlaceholder: { en: 'Tell us more about your inquiry...', es: 'Cuéntanos más sobre tu consulta...' },
  contactFormSubmit: { en: 'Send Message', es: 'Enviar Mensaje' },
  contactFormSending: { en: 'Sending...', es: 'Enviando...' },
  contactSuccessMessage: { en: 'Message sent successfully!', es: '¡Mensaje enviado exitosamente!' },
  contactErrorMessage: { en: 'Failed to send message. Please try again.', es: 'Error al enviar mensaje. Intenta de nuevo.' },
  contactThankYouTitle: { en: 'Thank you!', es: '¡Gracias!' },
  contactThankYouText: { en: 'We\'ve received your message and will get back to you soon.', es: 'Hemos recibido tu mensaje y te responderemos pronto.' },
  contactBackToHome: { en: 'Back to Home', es: 'Volver al Inicio' },
  contactSendAnother: { en: 'Send Another Message', es: 'Enviar Otro Mensaje' },
  
  // Help Page
  helpTitle: { en: 'Help Center', es: 'Centro de Ayuda' },
  helpBackToHome: { en: 'Back to Home', es: 'Volver al Inicio' },
  helpHeroTitle: { en: 'How can we help you?', es: '¿Cómo podemos ayudarte?' },
  helpHeroSubtitle: { en: 'Find answers to common questions or contact our support team', es: 'Encuentra respuestas a preguntas comunes o contacta a nuestro equipo' },
  helpSearchPlaceholder: { en: 'Search for help...', es: 'Buscar ayuda...' },
  helpContactSupport: { en: 'Contact Support', es: 'Contactar Soporte' },
  helpContactSupportDesc: { en: 'Get help from our team', es: 'Obtén ayuda de nuestro equipo' },
  helpBrowseFAQ: { en: 'Browse FAQ', es: 'Ver Preguntas Frecuentes' },
  helpBrowseFAQDesc: { en: 'Find quick answers', es: 'Encuentra respuestas rápidas' },
  helpVideoTutorials: { en: 'Video Tutorials', es: 'Video Tutoriales' },
  helpVideoTutorialsDesc: { en: 'Coming soon', es: 'Próximamente' },
  helpFAQTitle: { en: 'Frequently Asked Questions', es: 'Preguntas Frecuentes' },
  helpCategoryGettingStarted: { en: 'Getting Started', es: 'Primeros Pasos' },
  helpCategoryQuotes: { en: 'Quotes & Calculations', es: 'Cotizaciones y Cálculos' },
  helpCategoryAccount: { en: 'Account', es: 'Cuenta' },
  helpCategoryTechnical: { en: 'Technical', es: 'Técnico' },
  helpFaq1Question: { en: 'What is Dubai Invest Pro?', es: '¿Qué es Dubai Invest Pro?' },
  helpFaq1Answer: { en: 'Dubai Invest Pro is a professional platform for real estate investment analysis in Dubai, offering ROI calculators, cashflow projections, and interactive maps.', es: 'Dubai Invest Pro es una plataforma profesional para análisis de inversión inmobiliaria en Dubai, ofreciendo calculadoras de ROI, proyecciones de flujo de caja y mapas interactivos.' },
  helpFaq2Question: { en: 'How do I create my first quote?', es: '¿Cómo creo mi primera cotización?' },
  helpFaq2Answer: { en: 'Navigate to the Cashflow Generator from the home page, configure your property details, payment plan, and appreciation settings, then save your quote.', es: 'Navega al Generador de Cashflow desde la página principal, configura los detalles de la propiedad, plan de pago y ajustes de apreciación, luego guarda tu cotización.' },
  helpFaq3Question: { en: 'Can I share quotes with my clients?', es: '¿Puedo compartir cotizaciones con mis clientes?' },
  helpFaq3Answer: { en: 'Yes! Each quote has a share button that generates a unique link. You can also customize which sections are visible to clients.', es: '¡Sí! Cada cotización tiene un botón de compartir que genera un enlace único. También puedes personalizar qué secciones son visibles para los clientes.' },
  helpFaq4Question: { en: 'How accurate are the projections?', es: '¿Qué tan precisas son las proyecciones?' },
  helpFaq4Answer: { en: 'Projections are based on the parameters you input. They are estimates for planning purposes and should not be considered financial advice.', es: 'Las proyecciones se basan en los parámetros que ingresas. Son estimaciones para fines de planificación y no deben considerarse asesoramiento financiero.' },
  helpFaq5Question: { en: 'What is the difference between OI, SI, and HO investors?', es: '¿Cuál es la diferencia entre inversores OI, SI y HO?' },
  helpFaq5Answer: { en: 'OI (Opportunity Investor) buys off-plan and exits before handover. SI (Secondary Investor) buys during construction. HO (Handover) investor holds through completion.', es: 'OI (Inversionista de Oportunidad) compra en planos y sale antes de la entrega. SI compra durante la construcción. HO mantiene hasta la entrega.' },
  helpFaq6Question: { en: 'How do I compare multiple quotes?', es: '¿Cómo comparo múltiples cotizaciones?' },
  helpFaq6Answer: { en: 'Go to My Quotes, select the quotes you want to compare, and click the Compare button to see a side-by-side analysis.', es: 'Ve a Mis Cotizaciones, selecciona las cotizaciones que quieres comparar y haz clic en el botón Comparar para ver un análisis lado a lado.' },
  helpFaq7Question: { en: 'How do I reset my password?', es: '¿Cómo restablezco mi contraseña?' },
  helpFaq7Answer: { en: 'On the login page, click "Forgot password?" and enter your email. You\'ll receive a link to create a new password.', es: 'En la página de inicio de sesión, haz clic en "¿Olvidaste tu contraseña?" e ingresa tu correo. Recibirás un enlace para crear una nueva contraseña.' },
  helpFaq8Question: { en: 'How do I update my profile information?', es: '¿Cómo actualizo mi información de perfil?' },
  helpFaq8Answer: { en: 'Go to Account Settings from the navigation menu. You can update your name, contact details, and theme preferences there.', es: 'Ve a Configuración de Cuenta desde el menú de navegación. Puedes actualizar tu nombre, datos de contacto y preferencias de tema allí.' },
  helpFaq9Question: { en: 'Why is the map not loading?', es: '¿Por qué no carga el mapa?' },
  helpFaq9Answer: { en: 'Make sure you\'re logged in and have a stable internet connection. Try refreshing the page or clearing your browser cache.', es: 'Asegúrate de estar conectado y tener una conexión estable a internet. Intenta refrescar la página o limpiar el caché del navegador.' },
  helpFaq10Question: { en: 'Is my data secure?', es: '¿Mis datos están seguros?' },
  helpFaq10Answer: { en: 'Yes, we use industry-standard encryption and security practices. Your data is stored securely and never shared with third parties without your consent.', es: 'Sí, usamos encriptación y prácticas de seguridad estándar de la industria. Tus datos se almacenan de forma segura y nunca se comparten con terceros sin tu consentimiento.' },
  helpNoResults: { en: 'No results found. Try a different search term.', es: 'No se encontraron resultados. Intenta con otro término.' },
  helpContactUs: { en: 'Contact Us', es: 'Contáctanos' },
  helpStillNeedHelp: { en: 'Still need help?', es: '¿Aún necesitas ayuda?' },
  helpStillNeedHelpDesc: { en: 'Our support team is ready to assist you', es: 'Nuestro equipo de soporte está listo para asistirte' },
  helpContactTeam: { en: 'Contact Our Team', es: 'Contactar a Nuestro Equipo' },
  
  // Configuration Center - Manager Components
  zonesManagement: { en: 'Zones Management', es: 'Gestión de Zonas' },
  addZone: { en: 'Add Zone', es: 'Agregar Zona' },
  searchZones: { en: 'Search zones...', es: 'Buscar zonas...' },
  noZonesFound: { en: 'No zones found. Create your first zone to get started.', es: 'No se encontraron zonas. Crea tu primera zona para comenzar.' },
  deleteZone: { en: 'Delete Zone', es: 'Eliminar Zona' },
  deleteZoneConfirm: { en: 'Are you sure you want to delete this zone? This action cannot be undone.', es: '¿Estás seguro de que quieres eliminar esta zona? Esta acción no se puede deshacer.' },
  errorDeletingZone: { en: 'Error deleting zone', es: 'Error al eliminar zona' },
  zoneDeleted: { en: 'Zone deleted', es: 'Zona eliminada' },
  zoneDeletedSuccess: { en: 'The zone has been successfully deleted.', es: 'La zona ha sido eliminada exitosamente.' },
  
  // Zone Form
  editZone: { en: 'Edit Zone', es: 'Editar Zona' },
  createNewZone: { en: 'Create New Zone', es: 'Crear Nueva Zona' },
  basicInformation: { en: 'Basic Information', es: 'Información Básica' },
  zoneName: { en: 'Zone Name', es: 'Nombre de la Zona' },
  zoneNamePlaceholder: { en: 'e.g. Downtown Dubai', es: 'ej. Downtown Dubai' },
  polygonColor: { en: 'Polygon Color', es: 'Color del Polígono' },
  tagline: { en: 'Tagline', es: 'Tagline' },
  taglinePlaceholder: { en: 'e.g. "The Center of the World"', es: 'ej. "El Centro del Mundo"' },
  zoneImage: { en: 'Zone Image (800×450px recommended)', es: 'Imagen de Zona (800×450px recomendado)' },
  clickOrPaste: { en: 'Click or Ctrl+V', es: 'Clic o Ctrl+V' },
  investmentProfile: { en: 'Investment Profile', es: 'Perfil de Inversión' },
  concept: { en: 'Concept', es: 'Concepto' },
  conceptPlaceholder: { en: 'e.g. The most prestigious and touristic square kilometer.', es: 'ej. El kilómetro cuadrado más prestigioso y turístico.' },
  propertyTypes: { en: 'Property Types', es: 'Tipos de Propiedad' },
  propertyTypesPlaceholder: { en: 'e.g. Residential Towers, Penthouses, Villas, Townhouses...', es: 'ej. Torres Residenciales, Penthouses, Villas, Townhouses...' },
  investmentFocus: { en: 'Investment Focus', es: 'Enfoque de Inversión' },
  investmentFocusPlaceholder: { en: 'e.g. Airbnb + Capital Preservation', es: 'ej. Airbnb + Preservación de Capital' },
  mainDeveloper: { en: 'Main Developer', es: 'Desarrollador Principal' },
  mainDeveloperPlaceholder: { en: 'e.g. Emaar', es: 'ej. Emaar' },
  maturityLevel: { en: 'Maturity Level', es: 'Nivel de Madurez' },
  maturityLabel: { en: 'Maturity Label', es: 'Etiqueta de Madurez' },
  maturityLabelPlaceholder: { en: 'e.g. Saturated / Scarcity', es: 'ej. Saturado / Escasez' },
  prices: { en: 'Prices', es: 'Precios' },
  minPrice: { en: 'Minimum Price', es: 'Precio Mínimo' },
  maxPrice: { en: 'Maximum Price', es: 'Precio Máximo' },
  ticket1brMin: { en: 'Ticket 1BR Minimum', es: 'Ticket 1BR Mínimo' },
  ticket1brMax: { en: 'Ticket 1BR Maximum', es: 'Ticket 1BR Máximo' },
  zonePolygon: { en: 'Zone Polygon', es: 'Polígono de la Zona' },
  drawPolygonInstruction: { en: 'Use the polygon tool to draw the zone boundary on the map', es: 'Usa la herramienta de polígono para dibujar el límite de la zona en el mapa' },
  updateZone: { en: 'Update Zone', es: 'Actualizar Zona' },
  createZone: { en: 'Create Zone', es: 'Crear Zona' },
  errorUploadingImage: { en: 'Error uploading image', es: 'Error al subir imagen' },
  couldNotUploadImage: { en: 'Could not upload the image. Please try again.', es: 'No se pudo subir la imagen. Intenta de nuevo.' },
  validationError: { en: 'Validation Error', es: 'Error de Validación' },
  zoneNameRequired: { en: 'Zone name is required', es: 'El nombre de la zona es requerido' },
  pleaseDrawPolygon: { en: 'Please draw a polygon on the map', es: 'Por favor dibuja un polígono en el mapa' },
  errorSavingZone: { en: 'Error saving zone', es: 'Error al guardar zona' },
  zoneSaved: { en: 'Zone saved', es: 'Zona guardada' },
  theZone: { en: 'The zone', es: 'La zona' },
  hasBeenSuccessfully: { en: 'has been successfully', es: 'ha sido exitosamente' },
  updated: { en: 'updated', es: 'actualizada' },
  created: { en: 'created', es: 'creada' },


  addHotspot: { en: 'Add Hotspot', es: 'Agregar Hotspot' },
  searchHotspots: { en: 'Search hotspots...', es: 'Buscar hotspots...' },
  noHotspotsFound: { en: 'No hotspots found. Create your first hotspot to get started.', es: 'No se encontraron hotspots. Crea tu primer hotspot para comenzar.' },
  deleteHotspot: { en: 'Delete Hotspot', es: 'Eliminar Hotspot' },
  deleteHotspotConfirm: { en: 'Are you sure you want to delete', es: '¿Estás seguro de que quieres eliminar' },
  errorFetchingHotspots: { en: 'Error fetching hotspots', es: 'Error al cargar hotspots' },
  errorDeletingHotspot: { en: 'Error deleting hotspot', es: 'Error al eliminar hotspot' },
  hotspotDeleted: { en: 'Hotspot deleted', es: 'Hotspot eliminado' },
  hotspotDeletedSuccess: { en: 'The hotspot has been successfully deleted.', es: 'El hotspot ha sido eliminado exitosamente.' },
  filterByCategory: { en: 'Filter by category', es: 'Filtrar por categoría' },
  allCategories: { en: 'All Categories', es: 'Todas las Categorías' },
  catLandmark: { en: 'Landmark', es: 'Punto de Referencia' },
  catDistrict: { en: 'District', es: 'Distrito' },
  catMasterplan: { en: 'Masterplan', es: 'Plan Maestro' },
  catResidential: { en: 'Residential', es: 'Residencial' },
  catWaterfront: { en: 'Waterfront', es: 'Frente al Mar' },
  catRetail: { en: 'Retail', es: 'Comercial' },
  catLeisure: { en: 'Leisure', es: 'Ocio' },
  catGolf: { en: 'Golf', es: 'Golf' },
  catInfrastructure: { en: 'Infrastructure', es: 'Infraestructura' },
  catHeritage: { en: 'Heritage', es: 'Patrimonio' },
  
  projectsManagement: { en: 'Projects Management', es: 'Gestión de Proyectos' },
  addProject: { en: 'Add Project', es: 'Agregar Proyecto' },
  searchProjects: { en: 'Search projects...', es: 'Buscar proyectos...' },
  noProjectsFound: { en: 'No projects found. Create your first project to get started.', es: 'No se encontraron proyectos. Crea tu primer proyecto para comenzar.' },
  deleteProject: { en: 'Delete Project', es: 'Eliminar Proyecto' },
  deleteProjectConfirm: { en: 'Are you sure you want to delete this project?', es: '¿Estás seguro de que quieres eliminar este proyecto?' },
  errorFetchingProjects: { en: 'Error fetching projects', es: 'Error al cargar proyectos' },
  errorDeletingProject: { en: 'Error deleting project', es: 'Error al eliminar proyecto' },
  projectDeleted: { en: 'Project deleted', es: 'Proyecto eliminado' },
  projectDeletedSuccess: { en: 'The project has been successfully deleted.', es: 'El proyecto ha sido eliminado exitosamente.' },
  unnamedProject: { en: 'Unnamed Project', es: 'Proyecto Sin Nombre' },
  startingPrice: { en: 'Starting Price', es: 'Precio Inicial' },
  
  developersManagement: { en: 'Developers Management', es: 'Gestión de Desarrolladores' },
  addDeveloper: { en: 'Add Developer', es: 'Agregar Desarrollador' },
  searchDevelopers: { en: 'Search developers...', es: 'Buscar desarrolladores...' },
  noDevelopersFound: { en: 'No developers found', es: 'No se encontraron desarrolladores' },
  deleteDeveloper: { en: 'Delete Developer', es: 'Eliminar Desarrollador' },
  deleteDeveloperConfirm: { en: 'Are you sure you want to delete this developer?', es: '¿Estás seguro de que quieres eliminar este desarrollador?' },
  errorLoadingDevelopers: { en: 'Error loading developers', es: 'Error al cargar desarrolladores' },
  errorDeletingDeveloper: { en: 'Error deleting developer', es: 'Error al eliminar desarrollador' },
  developerDeleted: { en: 'Developer deleted', es: 'Desarrollador eliminado' },
  logo: { en: 'Logo', es: 'Logo' },
  founded: { en: 'Founded', es: 'Fundado' },
  projects: { en: 'Projects', es: 'Proyectos' },
  unitsSold: { en: 'Units Sold', es: 'Unidades Vendidas' },
  onTimePercent: { en: 'On-Time %', es: '% a Tiempo' },
  
  landmarksManagement: { en: 'Landmarks Management', es: 'Gestión de Landmarks' },
  addLandmark: { en: 'Add Landmark', es: 'Agregar Landmark' },
  searchLandmarks: { en: 'Search landmarks...', es: 'Buscar landmarks...' },
  noLandmarksFound: { en: 'No landmarks found', es: 'No se encontraron landmarks' },
  loadingLandmarks: { en: 'Loading landmarks', es: 'Cargando landmarks' },
  landmarksDescription: { en: 'Manage photo points for large area views', es: 'Gestiona puntos de foto para vistas de grandes áreas' },
  deleteLandmark: { en: 'Delete Landmark', es: 'Eliminar Landmark' },
  deleteLandmarkConfirm: { en: 'Are you sure you want to delete', es: '¿Estás seguro de que quieres eliminar' },
  errorDeletingLandmark: { en: 'Error deleting landmark', es: 'Error al eliminar landmark' },
  landmarkDeleted: { en: 'Landmark deleted', es: 'Landmark eliminado' },
  hasBeenDeleted: { en: 'has been deleted', es: 'ha sido eliminado' },
  image: { en: 'Image', es: 'Imagen' },
  
  // Presets Manager (unique keys only)
  appreciationPresetsManager: { en: 'Appreciation Presets', es: 'Presets de Apreciación' },
  appreciationPresetsDesc: { en: 'Custom capital appreciation profiles for cashflow calculations', es: 'Perfiles personalizados de apreciación de capital para cálculos de flujo de caja' },
  createPreset: { en: 'Create Preset', es: 'Crear Preset' },
  createAppreciationPreset: { en: 'Create Appreciation Preset', es: 'Crear Preset de Apreciación' },
  editAppreciationPreset: { en: 'Edit Appreciation Preset', es: 'Editar Preset de Apreciación' },
  presetNameLabel: { en: 'Preset Name', es: 'Nombre del Preset' },
  presetNamePlaceholder: { en: 'e.g. Conservative Growth', es: 'ej. Crecimiento Conservador' },
  constructionAppreciation: { en: 'Construction Appreciation', es: 'Apreciación de Construcción' },
  growthAppreciation: { en: 'Growth Appreciation', es: 'Apreciación de Crecimiento' },
  matureAppreciation: { en: 'Mature Appreciation', es: 'Apreciación Madura' },
  growthPeriod: { en: 'Growth Period', es: 'Período de Crecimiento' },
  savePresetBtn: { en: 'Save Preset', es: 'Guardar Preset' },
  updatePreset: { en: 'Update Preset', es: 'Actualizar Preset' },
  nameRequired: { en: 'Name required', es: 'Nombre requerido' },
  pleaseEnterPresetName: { en: 'Please enter a preset name', es: 'Por favor ingresa un nombre de preset' },
  noPresetsYet: { en: 'No Presets Yet', es: 'Sin Presets Aún' },
  createFirstPreset: { en: 'Create your first appreciation preset to use in the Cashflow Generator', es: 'Crea tu primer preset de apreciación para usar en el Generador de Cashflow' },
  createYourFirstPreset: { en: 'Create Your First Preset', es: 'Crea Tu Primer Preset' },
  constructionPercentLabel: { en: 'Construction %', es: 'Construcción %' },
  growthPercentLabel: { en: 'Growth %', es: 'Crecimiento %' },
  maturePercent: { en: 'Mature %', es: 'Maduro %' },
  rentGrowthLabel: { en: 'Rent Growth', es: 'Crecimiento Renta' },
  yrs: { en: 'yrs', es: 'años' },
  yearsLabel: { en: 'Years', es: 'Años' },


  // Common (only new keys not already defined)
  title: { en: 'Title', es: 'Título' },
  category: { en: 'Category', es: 'Categoría' },
  location: { en: 'Location', es: 'Ubicación' },
  actions: { en: 'Actions', es: 'Acciones' },
  actionCannotBeUndone: { en: 'This action cannot be undone.', es: 'Esta acción no se puede deshacer.' },
  loading: { en: 'Loading', es: 'Cargando' },
  
  // Home Dashboard - Wealth Advisor Edition
  goodMorning: { en: 'Good morning', es: 'Buenos días' },
  goodAfternoon: { en: 'Good afternoon', es: 'Buenas tardes' },
  goodEvening: { en: 'Good evening', es: 'Buenas noches' },
  marketPulse: { en: 'Market Pulse', es: 'Pulso del Mercado' },
  dubaiYield: { en: 'Dubai Avg Yield', es: 'Yield Promedio Dubai' },
  mortgageRates: { en: 'Mortgage Rates', es: 'Tasas Hipotecarias' },
  topArea: { en: 'Top Area', es: 'Zona Top' },
  activeProposals: { en: 'Active Proposals', es: 'Propuestas Activas' },
  pipelineVolume: { en: 'Pipeline Volume', es: 'Volumen Pipeline' },
  potentialCommission: { en: 'Potential Commission', es: 'Comisión Potencial' },
  thisMonth: { en: 'This month', es: 'Este mes' },
  totalDeals: { en: 'Total deals', es: 'Total de tratos' },
  ofVolume: { en: 'of volume', es: 'del volumen' },
  createStrategy: { en: 'Create Strategy', es: 'Crear Estrategia' },
  createStrategyDesc: { en: 'New client proposal & analysis', es: 'Nueva propuesta y análisis para cliente' },
  compareOpportunities: { en: 'Compare Opportunities', es: 'Comparar Oportunidades' },
  compareOpportunitiesDesc: { en: 'Side-by-side ROI analysis', es: 'Análisis ROI lado a lado' },
  marketIntelligence: { en: 'Market Intelligence', es: 'Inteligencia de Mercado' },
  marketIntelligenceDesc: { en: 'Area heatmaps & trends', es: 'Mapas de calor y tendencias por zona' },
  startNew: { en: 'Start New +', es: 'Nuevo +' },
  analyze: { en: 'Analyze >', es: 'Analizar >' },
  explore: { en: 'Explore >', es: 'Explorar >' },
  activeOpportunities: { en: 'Active Opportunities', es: 'Oportunidades Activas' },
  clientProject: { en: 'Client / Project', es: 'Cliente / Proyecto' },
  dealValue: { en: 'Deal Value', es: 'Valor del Trato' },
  keyStat: { en: 'Key Stat', es: 'Métrica Clave' },
  statusDraft: { en: 'Draft', es: 'Borrador' },
  statusPresented: { en: 'Presented', es: 'Presentado' },
  statusNegotiating: { en: 'Negotiating', es: 'Negociando' },
  statusSold: { en: 'Sold', es: 'Vendido' },
  noOpportunities: { en: 'No opportunities yet. Create your first proposal.', es: 'Sin oportunidades aún. Crea tu primera propuesta.' },
  createFirst: { en: 'Create First Proposal', es: 'Crear Primera Propuesta' },
  checkOutProperty: { en: 'Check out this investment property', es: 'Mira esta propiedad de inversión' },
  property: { en: 'Property', es: 'Propiedad' },
  errorUpdatingStatus: { en: 'Error updating status', es: 'Error actualizando estado' },
  statusUpdated: { en: 'Status updated', es: 'Estado actualizado' },
  
  // Business Settings & Market Pulse Modal
  businessSettings: { en: 'Business Settings', es: 'Configuración de Negocio' },
  commissionRate: { en: 'Commission Rate', es: 'Tasa de Comisión' },
  commissionRateDesc: { en: 'Your commission percentage for potential earnings calculation', es: 'Tu porcentaje de comisión para cálculo de ganancias potenciales' },
  marketPulseSettings: { en: 'Market Pulse Settings', es: 'Configuración de Market Pulse' },
  editMarketData: { en: 'Edit Market Data', es: 'Editar Datos de Mercado' },
  
  // Deal Table Filters
  filterByStatus: { en: 'Filter by Status', es: 'Filtrar por Estado' },
  allStatuses: { en: 'All Statuses', es: 'Todos los Estados' },
  dateRange: { en: 'Date Range', es: 'Rango de Fechas' },
  thisWeek: { en: 'This Week', es: 'Esta Semana' },
  last30Days: { en: 'Last 30 Days', es: 'Últimos 30 Días' },
  allTime: { en: 'All Time', es: 'Todo el Tiempo' },
  saveFailed: { en: 'Save failed', es: 'Error al guardar' },
  saved: { en: 'Saved', es: 'Guardado' },
  saving: { en: 'Saving...', es: 'Guardando...' },
  
  // Quick Search & Pipeline Analytics
  searchPlaceholder: { en: 'Search client, project, or developer...', es: 'Buscar cliente, proyecto o desarrollador...' },
  pipelineAnalytics: { en: 'Pipeline Analytics', es: 'Análisis de Pipeline' },
  lastSixMonths: { en: 'Last 6 Months', es: 'Últimos 6 Meses' },
  dealVolume: { en: 'Deal Volume', es: 'Volumen de Tratos' },
  earnedCommission: { en: 'Earned Commission', es: 'Comisión Ganada' },
  soldDeals: { en: 'Sold Deals', es: 'Tratos Cerrados' },
  deals: { en: 'Deals', es: 'Tratos' },
  pending: { en: 'Pending', es: 'Pendiente' },
  closedDeals: { en: 'Closed deals', es: 'Tratos cerrados' },
  totalQuotes: { en: 'Total Quotes', es: 'Total Cotizaciones' },
  compare: { en: 'Compare', es: 'Comparar' },
  quotesSelected: { en: 'quotes selected', es: 'cotizaciones seleccionadas' },
  min2Max4: { en: 'min 2, max 4', es: 'mín 2, máx 4' },
  compareSelected: { en: 'Compare Selected', es: 'Comparar Seleccionados' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) return key;
    return translation[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
