import { useMemo, useRef, useCallback } from "react";

interface ExitPoint {
  id: string;
  label: string;
  monthsFromBooking: number;
  isAutoGenerated: boolean;
  exitValue: number;
  appreciationPercent: number;
}

interface ExitTimelineProps {
  exits: ExitPoint[];
  totalMonths: number;
  bookingDate: Date;
  currency: string;
  onAddExit?: (monthsFromBooking: number) => void;
}

export const ExitTimeline = ({ exits, totalMonths, bookingDate, currency, onAddExit }: ExitTimelineProps) => {
  const timelineRef = useRef<HTMLDivElement>(null);

  const timelineMarkers = useMemo(() => {
    return exits.map(exit => ({
      ...exit,
      position: (exit.monthsFromBooking / totalMonths) * 100,
      date: (() => {
        const date = new Date(bookingDate);
        date.setMonth(date.getMonth() + exit.monthsFromBooking);
        return date.toLocaleDateString('en-US', { month: 'short', year: '2-digit' });
      })(),
    }));
  }, [exits, totalMonths, bookingDate]);

  const handleTimelineClick = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    if (!onAddExit || !timelineRef.current) return;
    
    const rect = timelineRef.current.getBoundingClientRect();
    const clickX = e.clientX - rect.left;
    const percentage = (clickX / rect.width) * 100;
    const clickedMonth = Math.round((percentage / 100) * totalMonths);
    
    // Don't add if too close to existing exit (within 2 months)
    const tooClose = exits.some(exit => Math.abs(exit.monthsFromBooking - clickedMonth) < 2);
    
    if (!tooClose && clickedMonth > 0 && clickedMonth < totalMonths) {
      onAddExit(clickedMonth);
    }
  }, [onAddExit, totalMonths, exits]);

  return (
    <div className="p-3 bg-[#0d1117] rounded-lg border border-[#2a3142]">
      <div className="flex items-center justify-between mb-3">
        <div className="text-[10px] text-gray-500 uppercase tracking-wider">Exit Timeline</div>
        {onAddExit && (
          <div className="text-[10px] text-[#CCFF00]/70">Click timeline to add exit</div>
        )}
      </div>
      
      {/* Timeline bar - clickable */}
      <div 
        ref={timelineRef}
        onClick={handleTimelineClick}
        className={`relative h-3 bg-[#1a1f2e] rounded-full mb-8 ${onAddExit ? 'cursor-crosshair hover:bg-[#252d3d] transition-colors' : ''}`}
      >
        {/* Progress gradient */}
        <div 
          className="absolute inset-y-0 left-0 rounded-full pointer-events-none"
          style={{
            width: '100%',
            background: 'linear-gradient(90deg, #CCFF00 0%, #22c55e 50%, #3b82f6 100%)',
            opacity: 0.25,
          }}
        />
        
        {/* Hover hint markers every 10% */}
        {onAddExit && Array.from({ length: 9 }, (_, i) => (i + 1) * 10).map(pct => (
          <div
            key={pct}
            className="absolute top-1/2 -translate-y-1/2 w-0.5 h-1.5 bg-gray-600/30 pointer-events-none"
            style={{ left: `${pct}%` }}
          />
        ))}
        
        {/* Exit markers */}
        {timelineMarkers.map((marker, index) => (
          <div
            key={marker.id}
            className="absolute top-1/2 -translate-y-1/2 flex flex-col items-center pointer-events-none"
            style={{ left: `${marker.position}%`, transform: 'translate(-50%, -50%)' }}
          >
            {/* Marker dot */}
            <div 
              className={`w-4 h-4 rounded-full border-2 shadow-lg ${
                marker.id === 'handover'
                  ? 'bg-blue-500 border-blue-400'
                  : marker.isAutoGenerated 
                    ? 'bg-[#CCFF00] border-[#CCFF00]/80' 
                    : 'bg-purple-500 border-purple-400'
              }`}
            />
            
            {/* Label below - alternating positions to avoid overlap */}
            <div 
              className={`absolute whitespace-nowrap text-center ${
                index % 2 === 0 ? 'top-5' : 'top-10'
              }`}
            >
              <div className="text-[10px] font-medium text-white">{marker.monthsFromBooking}mo</div>
              <div className="text-[9px] text-gray-500">{marker.date}</div>
              <div className="text-[9px] text-green-400 font-mono">+{marker.appreciationPercent.toFixed(0)}%</div>
            </div>
          </div>
        ))}
      </div>
      
      {/* Start and end labels */}
      <div className="flex justify-between text-[10px] text-gray-500 mt-10">
        <span>Booking</span>
        <span>Handover ({totalMonths}mo)</span>
      </div>
      
      {/* Legend */}
      <div className="flex items-center justify-center gap-4 mt-3 pt-2 border-t border-[#2a3142]/50">
        <div className="flex items-center gap-1.5">
          <div className="w-2.5 h-2.5 rounded-full bg-[#CCFF00]" />
          <span className="text-[9px] text-gray-500">Auto</span>
        </div>
        <div className="flex items-center gap-1.5">
          <div className="w-2.5 h-2.5 rounded-full bg-purple-500" />
          <span className="text-[9px] text-gray-500">Custom</span>
        </div>
        <div className="flex items-center gap-1.5">
          <div className="w-2.5 h-2.5 rounded-full bg-blue-500" />
          <span className="text-[9px] text-gray-500">Handover</span>
        </div>
      </div>
    </div>
  );
};
