import { useMemo, useRef, useCallback } from "react";

interface ExitPoint {
  id: string;
  label: string;
  monthsFromBooking: number;
  isAutoGenerated: boolean;
  exitValue: number;
  appreciationPercent: number;
}

interface ExitTimelineProps {
  exits: ExitPoint[];
  totalMonths: number;
  bookingDate: Date;
  currency: string;
  minimumThreshold?: number;
  onAddExit?: (monthsFromBooking: number) => void;
}

export const ExitTimeline = ({ exits, totalMonths, bookingDate, currency, minimumThreshold = 30, onAddExit }: ExitTimelineProps) => {
  const timelineRef = useRef<HTMLDivElement>(null);

  // Calculate threshold position on timeline based on payment percentage
  // Threshold represents min % paid before developer allows resale
  const thresholdPosition = useMemo(() => {
    // Simple approximation: if threshold is X%, we assume the exit point 
    // at roughly X% of timeline would have paid that amount
    return Math.min(minimumThreshold, 100);
  }, [minimumThreshold]);

  const timelineMarkers = useMemo(() => {
    return exits.map(exit => ({
      ...exit,
      position: (exit.monthsFromBooking / totalMonths) * 100,
      date: (() => {
        const date = new Date(bookingDate);
        date.setMonth(date.getMonth() + exit.monthsFromBooking);
        return date.toLocaleDateString('en-US', { month: 'short', year: '2-digit' });
      })(),
      // Check if this exit meets the minimum threshold
      meetsThreshold: (exit.monthsFromBooking / totalMonths) * 100 >= thresholdPosition,
    }));
  }, [exits, totalMonths, bookingDate, thresholdPosition]);

  const handleTimelineClick = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    if (!onAddExit || !timelineRef.current) return;
    
    const rect = timelineRef.current.getBoundingClientRect();
    const clickX = e.clientX - rect.left;
    const percentage = (clickX / rect.width) * 100;
    const clickedMonth = Math.round((percentage / 100) * totalMonths);
    
    // Don't add if too close to existing exit (within 2 months)
    const tooClose = exits.some(exit => Math.abs(exit.monthsFromBooking - clickedMonth) < 2);
    
    if (!tooClose && clickedMonth > 0 && clickedMonth < totalMonths) {
      onAddExit(clickedMonth);
    }
  }, [onAddExit, totalMonths, exits]);

  return (
    <div className="p-3 bg-theme-bg-alt rounded-lg border border-theme-border">
      <div className="flex items-center justify-between mb-3">
        <div className="text-[10px] text-theme-text-muted uppercase tracking-wider">Exit Timeline</div>
        {onAddExit && (
          <div className="text-[10px] text-theme-accent/70">Click timeline to add exit</div>
        )}
      </div>
      
      {/* Timeline bar - clickable */}
      <div 
        ref={timelineRef}
        onClick={handleTimelineClick}
        className={`relative h-3 bg-theme-card rounded-full mb-8 ${onAddExit ? 'cursor-crosshair hover:bg-theme-card-alt transition-colors' : ''}`}
      >
        {/* Progress gradient */}
        <div 
          className="absolute inset-y-0 left-0 rounded-full pointer-events-none"
          style={{
            width: '100%',
            background: 'linear-gradient(90deg, hsl(var(--theme-accent)) 0%, hsl(142 71% 45%) 50%, hsl(221 83% 53%) 100%)',
            opacity: 0.25,
          }}
        />
        
        {/* Threshold indicator line */}
        <div
          className="absolute top-1/2 -translate-y-1/2 h-6 w-0.5 pointer-events-none"
          style={{ 
            left: `${thresholdPosition}%`,
            background: 'repeating-linear-gradient(to bottom, hsl(var(--theme-accent)) 0, hsl(var(--theme-accent)) 2px, transparent 2px, transparent 4px)',
          }}
        />
        <div
          className="absolute -bottom-5 text-[9px] text-theme-accent whitespace-nowrap pointer-events-none"
          style={{ left: `${thresholdPosition}%`, transform: 'translateX(-50%)' }}
        >
          {minimumThreshold}% min
        </div>
        
        {/* Hover hint markers every 10% */}
        {onAddExit && Array.from({ length: 9 }, (_, i) => (i + 1) * 10).map(pct => (
          <div
            key={pct}
            className="absolute top-1/2 -translate-y-1/2 w-0.5 h-1.5 bg-theme-text-muted/30 pointer-events-none"
            style={{ left: `${pct}%` }}
          />
        ))}
        
        {/* Exit markers */}
        {timelineMarkers.map((marker, index) => (
          <div
            key={marker.id}
            className="absolute top-1/2 -translate-y-1/2 flex flex-col items-center pointer-events-none"
            style={{ left: `${marker.position}%`, transform: 'translate(-50%, -50%)' }}
          >
            {/* Marker dot */}
            <div 
              className={`w-4 h-4 rounded-full border-2 shadow-lg ${
                marker.id === 'handover'
                  ? 'bg-blue-500 border-blue-400'
                  : !marker.meetsThreshold
                    ? 'bg-red-500/60 border-red-400/60'
                    : marker.isAutoGenerated 
                      ? 'bg-theme-accent border-theme-accent/80' 
                      : 'bg-purple-500 border-purple-400'
              }`}
            />
            
            {/* Label below - alternating positions to avoid overlap */}
            <div 
              className={`absolute whitespace-nowrap text-center ${
                index % 2 === 0 ? 'top-5' : 'top-10'
              }`}
            >
              <div className={`text-[10px] font-medium ${!marker.meetsThreshold ? 'text-red-400' : 'text-theme-text'}`}>{marker.monthsFromBooking}mo</div>
              <div className="text-[9px] text-theme-text-muted">{marker.date}</div>
              <div className={`text-[9px] font-mono ${!marker.meetsThreshold ? 'text-red-400' : 'text-green-400'}`}>+{marker.appreciationPercent.toFixed(0)}%</div>
            </div>
          </div>
        ))}
      </div>
      
      {/* Start and end labels */}
      <div className="flex justify-between text-[10px] text-theme-text-muted mt-10">
        <span>Booking</span>
        <span>Handover ({totalMonths}mo)</span>
      </div>
      
      {/* Legend */}
      <div className="flex items-center justify-center gap-4 mt-3 pt-2 border-t border-theme-border/50">
        <div className="flex items-center gap-1.5">
          <div className="w-2.5 h-2.5 rounded-full bg-theme-accent" />
          <span className="text-[9px] text-theme-text-muted">Auto</span>
        </div>
        <div className="flex items-center gap-1.5">
          <div className="w-2.5 h-2.5 rounded-full bg-purple-500" />
          <span className="text-[9px] text-theme-text-muted">Custom</span>
        </div>
        <div className="flex items-center gap-1.5">
          <div className="w-2.5 h-2.5 rounded-full bg-blue-500" />
          <span className="text-[9px] text-theme-text-muted">Handover</span>
        </div>
        <div className="flex items-center gap-1.5">
          <div className="w-2.5 h-2.5 rounded-full bg-red-500/60" />
          <span className="text-[9px] text-theme-text-muted">Below min</span>
        </div>
      </div>
    </div>
  );
};
