import { useState, useCallback, useMemo } from "react";
import { LogOut, Plus, Trash2, Calendar, Sparkles, Pencil, Check, X, Save, FolderOpen, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Input } from "@/components/ui/input";
import { Slider } from "@/components/ui/slider";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { ConfiguratorSectionProps } from "./types";
import { formatCurrency } from "../currencyUtils";
import { ExitTimeline } from "./ExitTimeline";
import { useExitPresets, ExitPreset } from "@/hooks/useExitPresets";

interface ExitScenario {
  id: string;
  label: string;
  monthsFromBooking: number;
  isAutoGenerated: boolean;
}

export const ExitsSection = ({ inputs, setInputs, currency }: ConfiguratorSectionProps) => {
  const [exitScenariosEnabled, setExitScenariosEnabled] = useState(
    inputs.enabledSections?.exitStrategy ?? true
  );
  const [customExits, setCustomExits] = useState<ExitScenario[]>([]);
  const [isAddingCustom, setIsAddingCustom] = useState(false);
  const [customMonths, setCustomMonths] = useState<number>(12);
  const [editingExitId, setEditingExitId] = useState<string | null>(null);
  const [editingMonths, setEditingMonths] = useState<number>(0);
  const [isSavingPreset, setIsSavingPreset] = useState(false);
  const [presetName, setPresetName] = useState('');
  
  const { presets, saving: savingPresets, savePreset, deletePreset, applyPreset } = useExitPresets();

  // Calculate months from booking to handover
  const bookingDate = useMemo(() => new Date(inputs.bookingYear, inputs.bookingMonth - 1), [inputs.bookingYear, inputs.bookingMonth]);
  const handoverQuarterMonth = useMemo(() => (inputs.handoverQuarter - 1) * 3 + 1, [inputs.handoverQuarter]);
  const handoverDate = useMemo(() => new Date(inputs.handoverYear, handoverQuarterMonth - 1), [inputs.handoverYear, handoverQuarterMonth]);
  const totalMonths = useMemo(() => Math.max(1, Math.round((handoverDate.getTime() - bookingDate.getTime()) / (1000 * 60 * 60 * 24 * 30))), [bookingDate, handoverDate]);

  // Auto-generate exits based on timeline - max 3 exits for 36 months or less
  const autoGeneratedExits = useMemo((): ExitScenario[] => {
    const exits: ExitScenario[] = [];
    
    if (totalMonths >= 24) {
      const exit1 = Math.round(totalMonths * 0.33);
      const exit2 = Math.round(totalMonths * 0.60);
      const exit3 = Math.round(totalMonths * 0.85);
      
      exits.push({ id: 'auto-early', label: `Month ${exit1}`, monthsFromBooking: exit1, isAutoGenerated: true });
      exits.push({ id: 'auto-mid', label: `Month ${exit2}`, monthsFromBooking: exit2, isAutoGenerated: true });
      exits.push({ id: 'auto-late', label: `Month ${exit3}`, monthsFromBooking: exit3, isAutoGenerated: true });
    } else if (totalMonths >= 18) {
      const exit1 = Math.round(totalMonths * 0.45);
      const exit2 = Math.round(totalMonths * 0.80);
      
      exits.push({ id: 'auto-mid', label: `Month ${exit1}`, monthsFromBooking: exit1, isAutoGenerated: true });
      exits.push({ id: 'auto-late', label: `Month ${exit2}`, monthsFromBooking: exit2, isAutoGenerated: true });
    } else if (totalMonths >= 12) {
      const exit1 = Math.round(totalMonths * 0.65);
      exits.push({ id: 'auto-late', label: `Month ${exit1}`, monthsFromBooking: exit1, isAutoGenerated: true });
    }
    
    exits.push({ id: 'handover', label: 'Handover', monthsFromBooking: totalMonths, isAutoGenerated: true });
    
    return exits;
  }, [totalMonths]);

  const allExits = useMemo(() => {
    return [...autoGeneratedExits, ...customExits].sort((a, b) => a.monthsFromBooking - b.monthsFromBooking);
  }, [autoGeneratedExits, customExits]);

  const getExitDetails = useCallback((monthsFromBooking: number) => {
    const exitPercent = (monthsFromBooking / totalMonths) * 100;
    const exitYears = monthsFromBooking / 12;
    
    const annualRate = inputs.constructionAppreciation ?? 12;
    const exitValue = inputs.basePrice * Math.pow(1 + annualRate / 100, exitYears);
    const appreciation = exitValue - inputs.basePrice;
    const appreciationPercent = (appreciation / inputs.basePrice) * 100;
    
    let equityPercent = inputs.downpaymentPercent;
    inputs.additionalPayments.forEach(p => {
      if (p.type === 'time' && p.triggerValue <= monthsFromBooking) {
        equityPercent += p.paymentPercent;
      } else if (p.type === 'construction' && p.triggerValue <= exitPercent) {
        equityPercent += p.paymentPercent;
      }
    });
    
    if (monthsFromBooking >= totalMonths) equityPercent = 100;
    
    const equityDeployed = inputs.basePrice * (equityPercent / 100);
    const profit = appreciation;
    const roe = equityDeployed > 0 ? (profit / equityDeployed) * 100 : 0;
    
    return { exitValue, appreciation, appreciationPercent, equityDeployed, equityPercent, profit, roe };
  }, [inputs, totalMonths]);

  const handleToggle = (enabled: boolean) => {
    setExitScenariosEnabled(enabled);
    setInputs(prev => ({
      ...prev,
      enabledSections: { ...prev.enabledSections, exitStrategy: enabled, longTermHold: prev.enabledSections?.longTermHold ?? true },
    }));
  };

  const handleAddCustomExit = (months?: number) => {
    const monthsToAdd = months ?? customMonths;
    if (monthsToAdd > 0 && monthsToAdd < totalMonths) {
      const newExit: ExitScenario = {
        id: `custom-${Date.now()}`,
        label: `Month ${monthsToAdd}`,
        monthsFromBooking: monthsToAdd,
        isAutoGenerated: false,
      };
      setCustomExits(prev => [...prev, newExit]);
      setIsAddingCustom(false);
      setCustomMonths(12);
    }
  };

  const handleRemoveExit = (exitId: string) => {
    setCustomExits(prev => prev.filter(e => e.id !== exitId));
  };

  const handleStartEdit = (exit: ExitScenario) => {
    setEditingExitId(exit.id);
    setEditingMonths(exit.monthsFromBooking);
  };

  const handleSaveEdit = (exitId: string) => {
    if (editingMonths > 0 && editingMonths < totalMonths) {
      setCustomExits(prev => prev.map(e => 
        e.id === exitId ? { ...e, monthsFromBooking: editingMonths, label: `Month ${editingMonths}` } : e
      ));
    }
    setEditingExitId(null);
  };

  const handleCancelEdit = () => setEditingExitId(null);

  const getExitDate = (monthsFromBooking: number): string => {
    const date = new Date(bookingDate);
    date.setMonth(date.getMonth() + monthsFromBooking);
    return date.toLocaleDateString('en-US', { month: 'short', year: 'numeric' });
  };

  const handleSavePreset = async () => {
    if (!presetName.trim()) return;
    const exitMonths = customExits.map(e => e.monthsFromBooking);
    const success = await savePreset(presetName.trim(), { exitMonths, minimumExitThreshold: inputs.minimumExitThreshold });
    if (success) { setIsSavingPreset(false); setPresetName(''); }
  };

  const handleLoadPreset = (preset: ExitPreset) => {
    const values = applyPreset(preset);
    const loadedExits: ExitScenario[] = values.exitMonths.map((months, index) => ({
      id: `preset-${Date.now()}-${index}`,
      label: `Month ${months}`,
      monthsFromBooking: months,
      isAutoGenerated: false,
    }));
    setCustomExits(loadedExits);
    setInputs(prev => ({ ...prev, minimumExitThreshold: values.minimumExitThreshold }));
  };

  const handleDeletePreset = async (e: React.MouseEvent, presetId: string) => {
    e.stopPropagation();
    await deletePreset(presetId);
  };

  const handleThresholdChange = (value: number[]) => {
    setInputs(prev => ({ ...prev, minimumExitThreshold: value[0] }));
  };

  const timelineExits = useMemo(() => {
    return allExits.map(exit => {
      const details = getExitDetails(exit.monthsFromBooking);
      return { ...exit, exitValue: details.exitValue, appreciationPercent: details.appreciationPercent };
    });
  }, [allExits, getExitDetails]);

  return (
    <div className="space-y-4">
      <div>
        <h3 className="text-lg font-semibold text-white mb-0.5">Exit Scenarios</h3>
        <p className="text-xs text-gray-500">Configure when you might exit this investment</p>
      </div>

      {/* Enable Toggle */}
      <div className="flex items-center justify-between p-3 bg-[#1a1f2e] rounded-lg border border-[#2a3142]">
        <div className="flex items-center gap-2">
          <LogOut className="w-4 h-4 text-[#CCFF00]" />
          <span className="text-sm text-gray-300">Enable Exit Analysis</span>
        </div>
        <Switch checked={exitScenariosEnabled} onCheckedChange={handleToggle} className="data-[state=checked]:bg-[#CCFF00]" />
      </div>

      {exitScenariosEnabled && (
        <>
          {/* Minimum Exit Threshold - MOVED UP with Slider */}
          <div className="p-3 bg-[#1a1f2e] rounded-xl border border-[#2a3142] space-y-3">
            <div className="flex justify-between items-center">
              <label className="text-sm text-gray-300">Minimum Exit Threshold</label>
              <span className="text-sm text-[#CCFF00] font-mono font-semibold">{inputs.minimumExitThreshold}%</span>
            </div>
            <Slider
              value={[inputs.minimumExitThreshold]}
              onValueChange={handleThresholdChange}
              min={20}
              max={80}
              step={5}
              className="w-full"
            />
            <div className="flex justify-between text-[10px] text-gray-500">
              <span>20%</span>
              <span>Min % paid before developer allows resale</span>
              <span>80%</span>
            </div>
          </div>

          {/* Presets Controls with Delete */}
          <div className="flex items-center gap-2">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline" size="sm" className="flex-1 h-8 text-xs bg-[#0d1117] border-[#2a3142] text-gray-300 justify-start">
                  <FolderOpen className="w-3 h-3 mr-1.5" />
                  Load preset...
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="start" className="w-56">
                {presets.length === 0 ? (
                  <div className="px-2 py-2 text-xs text-gray-500">No presets saved</div>
                ) : (
                  presets.map(preset => (
                    <DropdownMenuItem key={preset.id} className="flex items-center justify-between group" onSelect={() => handleLoadPreset(preset)}>
                      <span className="text-xs">{preset.name} ({preset.exit_months.length} exits)</span>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={(e) => handleDeletePreset(e, preset.id)}
                        className="h-5 w-5 p-0 opacity-0 group-hover:opacity-100 text-gray-500 hover:text-red-400"
                      >
                        <Trash2 className="w-3 h-3" />
                      </Button>
                    </DropdownMenuItem>
                  ))
                )}
              </DropdownMenuContent>
            </DropdownMenu>
            
            {!isSavingPreset ? (
              <Button
                variant="outline"
                size="sm"
                onClick={() => setIsSavingPreset(true)}
                disabled={customExits.length === 0}
                className="h-8 text-xs border-[#2a3142] text-gray-400 hover:text-white"
              >
                <Save className="w-3 h-3 mr-1" />
                Save
              </Button>
            ) : (
              <div className="flex items-center gap-1.5">
                <Input
                  value={presetName}
                  onChange={(e) => setPresetName(e.target.value)}
                  placeholder="Preset name"
                  className="w-28 h-8 text-xs bg-[#0d1117] border-[#2a3142] text-white"
                />
                <Button size="sm" onClick={handleSavePreset} disabled={!presetName.trim() || savingPresets} className="h-8 px-2 bg-[#CCFF00] text-black hover:bg-[#CCFF00]/90">
                  <Check className="w-3 h-3" />
                </Button>
                <Button variant="ghost" size="sm" onClick={() => { setIsSavingPreset(false); setPresetName(''); }} className="h-8 px-2 text-gray-500">
                  <X className="w-3 h-3" />
                </Button>
              </div>
            )}
          </div>

          {/* Interactive Visual Timeline */}
          <ExitTimeline 
            exits={timelineExits}
            totalMonths={totalMonths}
            bookingDate={bookingDate}
            currency={currency}
            onAddExit={handleAddCustomExit}
          />

          {/* Timeline Info */}
          <div className="flex items-center justify-between p-2 bg-[#1a1f2e]/50 rounded-lg border border-[#2a3142]/50">
            <div className="flex items-center gap-2 text-xs text-gray-400">
              <Calendar className="w-3.5 h-3.5 shrink-0" />
              <span>{totalMonths} month construction</span>
            </div>
            <div className="flex items-center gap-1.5">
              <Sparkles className="w-3 h-3 text-[#CCFF00]" />
              <span className="text-xs text-[#CCFF00]">{autoGeneratedExits.length} auto + {customExits.length} custom</span>
            </div>
          </div>

          {/* Exit Scenarios List */}
          <div className="space-y-2">
            {allExits.map((exit) => {
              const details = getExitDetails(exit.monthsFromBooking);
              const isEditing = editingExitId === exit.id;
              const isMinimumMet = details.equityPercent >= inputs.minimumExitThreshold;
              
              return (
                <div
                  key={exit.id}
                  className={`p-3 rounded-xl border ${exit.isAutoGenerated ? 'bg-[#1a1f2e] border-[#2a3142]' : 'bg-[#1a1f2e] border-purple-500/30'}`}
                >
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                      {isEditing ? (
                        <div className="flex items-center gap-1.5">
                          <span className="text-xs text-gray-400">Month:</span>
                          <Input
                            type="number"
                            value={editingMonths}
                            onChange={(e) => setEditingMonths(parseInt(e.target.value) || 0)}
                            min={1}
                            max={totalMonths - 1}
                            className="w-16 h-6 text-xs bg-[#0d1117] border-[#2a3142] text-white font-mono"
                          />
                          <Button variant="ghost" size="sm" onClick={() => handleSaveEdit(exit.id)} className="h-6 w-6 p-0 text-green-400 hover:text-green-300">
                            <Check className="w-3.5 h-3.5" />
                          </Button>
                          <Button variant="ghost" size="sm" onClick={handleCancelEdit} className="h-6 w-6 p-0 text-gray-500 hover:text-gray-300">
                            <X className="w-3.5 h-3.5" />
                          </Button>
                        </div>
                      ) : (
                        <>
                          <span className="text-sm font-medium text-white">{exit.label}</span>
                          <span className="text-xs text-gray-500">• {getExitDate(exit.monthsFromBooking)}</span>
                          {!exit.isAutoGenerated && (
                            <span className="text-[10px] bg-purple-500/20 text-purple-400 px-1.5 py-0.5 rounded">Custom</span>
                          )}
                        </>
                      )}
                    </div>
                    
                    {!exit.isAutoGenerated && !isEditing && (
                      <div className="flex items-center gap-1">
                        <Button variant="ghost" size="sm" onClick={() => handleStartEdit(exit)} className="h-6 w-6 p-0 text-gray-500 hover:text-blue-400">
                          <Pencil className="w-3.5 h-3.5" />
                        </Button>
                        <Button variant="ghost" size="sm" onClick={() => handleRemoveExit(exit.id)} className="h-6 w-6 p-0 text-gray-500 hover:text-red-400">
                          <Trash2 className="w-3.5 h-3.5" />
                        </Button>
                      </div>
                    )}
                  </div>

                  <div className="grid grid-cols-3 gap-2">
                    <div className="bg-[#0d1117] rounded-lg p-2 text-center">
                      <div className="text-sm font-mono text-white font-semibold">{formatCurrency(details.exitValue, currency)}</div>
                      <div className="text-[10px] text-gray-500">Exit Value</div>
                    </div>
                    <div className="bg-[#0d1117] rounded-lg p-2 text-center">
                      <div className="text-sm font-mono text-green-400 font-semibold">+{details.appreciationPercent.toFixed(1)}%</div>
                      <div className="text-[10px] text-gray-500">Appreciation</div>
                    </div>
                    <div className="bg-[#0d1117] rounded-lg p-2 text-center">
                      <div className="text-sm font-mono text-[#CCFF00] font-semibold">{details.roe.toFixed(0)}%</div>
                      <div className="text-[10px] text-gray-500">Return on Equity</div>
                    </div>
                  </div>

                  <div className="flex items-center justify-between mt-2 pt-2 border-t border-[#2a3142]/50 text-xs">
                    <span className="text-gray-500">Equity: {formatCurrency(details.equityDeployed, currency)} ({details.equityPercent.toFixed(0)}%)</span>
                    {!isMinimumMet && (
                      <span className="flex items-center gap-1 text-amber-400">
                        <AlertTriangle className="w-3 h-3" />
                        Below {inputs.minimumExitThreshold}%
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Add Custom Exit */}
          {!isAddingCustom ? (
            <Button
              variant="outline"
              size="sm"
              onClick={() => setIsAddingCustom(true)}
              className="w-full h-9 text-xs bg-[#0d1117] border-purple-500/30 text-purple-400 hover:bg-purple-500/10"
            >
              <Plus className="w-3.5 h-3.5 mr-1.5" />
              Add Custom Exit Point
            </Button>
          ) : (
            <div className="p-3 bg-[#1a1f2e] rounded-xl border border-purple-500/30 space-y-3">
              <div className="flex items-center gap-2">
                <label className="text-xs text-gray-400 shrink-0">Exit at month:</label>
                <Input
                  type="number"
                  value={customMonths}
                  onChange={(e) => setCustomMonths(parseInt(e.target.value) || 0)}
                  min={1}
                  max={totalMonths - 1}
                  className="w-20 h-8 text-sm bg-[#0d1117] border-[#2a3142] text-white font-mono"
                />
                <span className="text-xs text-gray-500">of {totalMonths} total</span>
              </div>
              <div className="flex gap-2">
                <Button size="sm" onClick={() => handleAddCustomExit()} disabled={customMonths <= 0 || customMonths >= totalMonths} className="flex-1 h-8 text-xs bg-purple-500 text-white hover:bg-purple-600">
                  Add Exit Point
                </Button>
                <Button variant="outline" size="sm" onClick={() => setIsAddingCustom(false)} className="h-8 text-xs border-[#2a3142] text-gray-400">
                  Cancel
                </Button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
};
