import { useMemo } from "react";
import { formatCurrency } from "../currencyUtils";

interface ExitPoint {
  id: string;
  label: string;
  monthsFromBooking: number;
  isAutoGenerated: boolean;
  exitValue: number;
  appreciationPercent: number;
}

interface ExitTimelineProps {
  exits: ExitPoint[];
  totalMonths: number;
  bookingDate: Date;
  currency: string;
}

export const ExitTimeline = ({ exits, totalMonths, bookingDate, currency }: ExitTimelineProps) => {
  const timelineMarkers = useMemo(() => {
    return exits.map(exit => ({
      ...exit,
      position: (exit.monthsFromBooking / totalMonths) * 100,
      date: (() => {
        const date = new Date(bookingDate);
        date.setMonth(date.getMonth() + exit.monthsFromBooking);
        return date.toLocaleDateString('en-US', { month: 'short', year: '2-digit' });
      })(),
    }));
  }, [exits, totalMonths, bookingDate]);

  return (
    <div className="p-3 bg-[#0d1117] rounded-lg border border-[#2a3142]">
      <div className="text-[10px] text-gray-500 uppercase tracking-wider mb-3">Exit Timeline</div>
      
      {/* Timeline bar */}
      <div className="relative h-2 bg-[#1a1f2e] rounded-full mb-6">
        {/* Progress gradient */}
        <div 
          className="absolute inset-y-0 left-0 rounded-full"
          style={{
            width: '100%',
            background: 'linear-gradient(90deg, #CCFF00 0%, #22c55e 50%, #3b82f6 100%)',
            opacity: 0.3,
          }}
        />
        
        {/* Exit markers */}
        {timelineMarkers.map((marker, index) => (
          <div
            key={marker.id}
            className="absolute top-1/2 -translate-y-1/2 flex flex-col items-center"
            style={{ left: `${marker.position}%` }}
          >
            {/* Marker dot */}
            <div 
              className={`w-3 h-3 rounded-full border-2 ${
                marker.isAutoGenerated 
                  ? 'bg-[#CCFF00] border-[#CCFF00]' 
                  : 'bg-blue-500 border-blue-500'
              }`}
            />
            
            {/* Label below - alternating positions to avoid overlap */}
            <div 
              className={`absolute whitespace-nowrap text-center ${
                index % 2 === 0 ? 'top-4' : 'top-8'
              }`}
            >
              <div className="text-[10px] font-medium text-white">{marker.monthsFromBooking}mo</div>
              <div className="text-[9px] text-gray-500">{marker.date}</div>
              <div className="text-[9px] text-green-400">+{marker.appreciationPercent.toFixed(0)}%</div>
            </div>
          </div>
        ))}
      </div>
      
      {/* Start and end labels */}
      <div className="flex justify-between text-[10px] text-gray-500 mt-8">
        <span>Booking</span>
        <span>Handover ({totalMonths}mo)</span>
      </div>
    </div>
  );
};
