import { useState, useEffect, useCallback, useMemo } from "react";
import { LogOut, Plus, Trash2, Calendar, Sparkles, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ConfiguratorSectionProps, months } from "./types";
import { formatCurrency } from "../currencyUtils";

interface ExitScenario {
  id: string;
  label: string;
  monthsFromBooking: number;
  isAutoGenerated: boolean;
}

export const ExitsSection = ({ inputs, setInputs, currency }: ConfiguratorSectionProps) => {
  const [exitScenariosEnabled, setExitScenariosEnabled] = useState(
    inputs.enabledSections?.exitStrategy ?? true
  );
  const [customExits, setCustomExits] = useState<ExitScenario[]>([]);
  const [isAddingCustom, setIsAddingCustom] = useState(false);
  const [customMonths, setCustomMonths] = useState<number>(12);

  // Calculate months from booking to handover
  const bookingDate = useMemo(() => new Date(inputs.bookingYear, inputs.bookingMonth - 1), [inputs.bookingYear, inputs.bookingMonth]);
  const handoverQuarterMonth = useMemo(() => (inputs.handoverQuarter - 1) * 3 + 1, [inputs.handoverQuarter]);
  const handoverDate = useMemo(() => new Date(inputs.handoverYear, handoverQuarterMonth - 1), [inputs.handoverYear, handoverQuarterMonth]);
  const totalMonths = useMemo(() => Math.max(1, Math.round((handoverDate.getTime() - bookingDate.getTime()) / (1000 * 60 * 60 * 24 * 30))), [bookingDate, handoverDate]);

  // Auto-generate exits based on timeline
  const autoGeneratedExits = useMemo((): ExitScenario[] => {
    const exits: ExitScenario[] = [];
    
    // Logic: space exits evenly, but always relative to handover
    // If ≥24 months: 3 exits (18mo from booking, 12mo before handover, 6mo before handover)
    // If 18-24 months: 2 exits (12mo, 6mo before handover)
    // If 12-18 months: 1 exit (6mo before handover)
    // If <12 months: handover only
    
    if (totalMonths >= 24) {
      // 18 months from booking
      exits.push({
        id: 'auto-18mo',
        label: '18 months from booking',
        monthsFromBooking: 18,
        isAutoGenerated: true,
      });
      // 12 months before handover
      exits.push({
        id: 'auto-12mo-before',
        label: '12 months before handover',
        monthsFromBooking: totalMonths - 12,
        isAutoGenerated: true,
      });
      // 6 months before handover
      exits.push({
        id: 'auto-6mo-before',
        label: '6 months before handover',
        monthsFromBooking: totalMonths - 6,
        isAutoGenerated: true,
      });
    } else if (totalMonths >= 18) {
      // 12 months before handover
      exits.push({
        id: 'auto-12mo-before',
        label: '12 months before handover',
        monthsFromBooking: totalMonths - 12,
        isAutoGenerated: true,
      });
      // 6 months before handover
      exits.push({
        id: 'auto-6mo-before',
        label: '6 months before handover',
        monthsFromBooking: totalMonths - 6,
        isAutoGenerated: true,
      });
    } else if (totalMonths >= 12) {
      // 6 months before handover
      exits.push({
        id: 'auto-6mo-before',
        label: '6 months before handover',
        monthsFromBooking: totalMonths - 6,
        isAutoGenerated: true,
      });
    }
    
    // Always include handover
    exits.push({
      id: 'handover',
      label: 'At handover',
      monthsFromBooking: totalMonths,
      isAutoGenerated: true,
    });
    
    return exits;
  }, [totalMonths]);

  // Combine auto and custom exits
  const allExits = useMemo(() => {
    return [...autoGeneratedExits, ...customExits].sort((a, b) => a.monthsFromBooking - b.monthsFromBooking);
  }, [autoGeneratedExits, customExits]);

  // Calculate exit details
  const getExitDetails = useCallback((monthsFromBooking: number) => {
    const exitPercent = (monthsFromBooking / totalMonths) * 100;
    const exitYears = monthsFromBooking / 12;
    
    // Simple appreciation calc (uses construction appreciation during construction)
    const annualRate = inputs.constructionAppreciation ?? 12;
    const exitValue = inputs.basePrice * Math.pow(1 + annualRate / 100, exitYears);
    const appreciation = exitValue - inputs.basePrice;
    const appreciationPercent = (appreciation / inputs.basePrice) * 100;
    
    // Calculate equity deployed at this point
    let equityPercent = inputs.downpaymentPercent;
    inputs.additionalPayments.forEach(p => {
      if (p.type === 'time' && p.triggerValue <= monthsFromBooking) {
        equityPercent += p.paymentPercent;
      } else if (p.type === 'construction' && p.triggerValue <= exitPercent) {
        equityPercent += p.paymentPercent;
      }
    });
    
    // If at handover, add the remaining percentage
    if (monthsFromBooking >= totalMonths) {
      equityPercent = 100;
    }
    
    const equityDeployed = inputs.basePrice * (equityPercent / 100);
    const profit = appreciation;
    const roe = equityDeployed > 0 ? (profit / equityDeployed) * 100 : 0;
    
    return {
      exitValue,
      appreciation,
      appreciationPercent,
      equityDeployed,
      equityPercent,
      profit,
      roe,
    };
  }, [inputs, totalMonths]);

  // Toggle handler
  const handleToggle = (enabled: boolean) => {
    setExitScenariosEnabled(enabled);
    setInputs(prev => ({
      ...prev,
      enabledSections: {
        ...prev.enabledSections,
        exitStrategy: enabled,
        longTermHold: prev.enabledSections?.longTermHold ?? true,
      },
    }));
  };

  // Add custom exit
  const handleAddCustomExit = () => {
    if (customMonths > 0 && customMonths < totalMonths) {
      const newExit: ExitScenario = {
        id: `custom-${Date.now()}`,
        label: `${customMonths} months from booking`,
        monthsFromBooking: customMonths,
        isAutoGenerated: false,
      };
      setCustomExits(prev => [...prev, newExit]);
      setIsAddingCustom(false);
      setCustomMonths(12);
    }
  };

  // Remove custom exit
  const handleRemoveExit = (exitId: string) => {
    setCustomExits(prev => prev.filter(e => e.id !== exitId));
  };

  // Format date for display
  const getExitDate = (monthsFromBooking: number): string => {
    const date = new Date(bookingDate);
    date.setMonth(date.getMonth() + monthsFromBooking);
    return date.toLocaleDateString('en-US', { month: 'short', year: 'numeric' });
  };

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-semibold text-white mb-1">Exit Scenarios</h3>
        <p className="text-sm text-gray-500">Configure when and how you might exit this investment</p>
      </div>

      {/* Enable Toggle */}
      <div className="flex items-center justify-between p-4 bg-[#1a1f2e] rounded-xl border border-[#2a3142]">
        <div className="flex items-center gap-2">
          <LogOut className="w-4 h-4 text-[#CCFF00]" />
          <span className="text-sm text-gray-300">Enable Exit Analysis</span>
        </div>
        <Switch
          checked={exitScenariosEnabled}
          onCheckedChange={handleToggle}
          className="data-[state=checked]:bg-[#CCFF00]"
        />
      </div>

      {exitScenariosEnabled && (
        <>
          {/* Timeline Info */}
          <div className="p-3 bg-[#0d1117] rounded-lg border border-[#2a3142]">
            <div className="flex items-center gap-2 text-xs text-gray-400">
              <Calendar className="w-3.5 h-3.5" />
              <span>
                {totalMonths} months from booking ({months.find(m => m.value === inputs.bookingMonth)?.label} {inputs.bookingYear}) 
                to handover (Q{inputs.handoverQuarter} {inputs.handoverYear})
              </span>
            </div>
          </div>

          {/* Auto-generated info */}
          <div className="p-3 bg-[#CCFF00]/10 rounded-lg border border-[#CCFF00]/30">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-[#CCFF00]" />
              <span className="text-sm text-[#CCFF00]">
                {autoGeneratedExits.length} exit points auto-generated
              </span>
            </div>
            <p className="text-xs text-gray-500 mt-1">
              Based on {totalMonths} months construction period
            </p>
          </div>

          {/* Exit Scenarios List */}
          <div className="space-y-3">
            {allExits.map((exit) => {
              const details = getExitDetails(exit.monthsFromBooking);
              const isMinimumMet = details.equityPercent >= inputs.minimumExitThreshold;
              
              return (
                <div
                  key={exit.id}
                  className={`p-4 rounded-xl border ${
                    exit.isAutoGenerated 
                      ? 'bg-[#1a1f2e] border-[#2a3142]' 
                      : 'bg-[#1a1f2e] border-[#CCFF00]/30'
                  }`}
                >
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium text-white">{exit.label}</span>
                        {!exit.isAutoGenerated && (
                          <span className="text-[10px] bg-[#CCFF00]/20 text-[#CCFF00] px-1.5 py-0.5 rounded">
                            Custom
                          </span>
                        )}
                      </div>
                      <span className="text-xs text-gray-500">{getExitDate(exit.monthsFromBooking)}</span>
                    </div>
                    {!exit.isAutoGenerated && (
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleRemoveExit(exit.id)}
                        className="h-6 w-6 p-0 text-gray-500 hover:text-red-400"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </Button>
                    )}
                  </div>

                  <div className="grid grid-cols-3 gap-3 text-center">
                    <div>
                      <div className="text-lg font-mono text-white font-bold">
                        {formatCurrency(details.exitValue, currency)}
                      </div>
                      <div className="text-[10px] text-gray-500">Exit Value</div>
                    </div>
                    <div>
                      <div className="text-lg font-mono text-green-400 font-bold">
                        +{details.appreciationPercent.toFixed(1)}%
                      </div>
                      <div className="text-[10px] text-gray-500">Appreciation</div>
                    </div>
                    <div>
                      <div className="text-lg font-mono text-[#CCFF00] font-bold">
                        {details.roe.toFixed(0)}%
                      </div>
                      <div className="text-[10px] text-gray-500">ROE</div>
                    </div>
                  </div>

                  <div className="mt-3 pt-3 border-t border-[#2a3142] flex items-center justify-between text-xs">
                    <span className="text-gray-500">
                      Equity: {formatCurrency(details.equityDeployed, currency)} ({details.equityPercent.toFixed(0)}%)
                    </span>
                    {!isMinimumMet && (
                      <span className="flex items-center gap-1 text-amber-400">
                        <AlertTriangle className="w-3 h-3" />
                        Below {inputs.minimumExitThreshold}% threshold
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Add Custom Exit */}
          {!isAddingCustom ? (
            <Button
              variant="outline"
              size="sm"
              onClick={() => setIsAddingCustom(true)}
              className="w-full h-9 text-xs bg-[#0d1117] border-[#CCFF00]/30 text-[#CCFF00] hover:bg-[#CCFF00]/20"
            >
              <Plus className="w-3.5 h-3.5 mr-1" />
              Add Custom Exit Point
            </Button>
          ) : (
            <div className="p-4 bg-[#1a1f2e] rounded-xl border border-[#CCFF00]/30 space-y-3">
              <div className="flex items-center gap-2">
                <label className="text-xs text-gray-400 shrink-0">Exit at month:</label>
                <Input
                  type="number"
                  value={customMonths}
                  onChange={(e) => setCustomMonths(parseInt(e.target.value) || 0)}
                  min={1}
                  max={totalMonths - 1}
                  className="w-20 h-8 text-sm bg-[#0d1117] border-[#2a3142] text-white font-mono"
                />
                <span className="text-xs text-gray-500">of {totalMonths} total</span>
              </div>
              <div className="flex gap-2">
                <Button
                  size="sm"
                  onClick={handleAddCustomExit}
                  disabled={customMonths <= 0 || customMonths >= totalMonths}
                  className="flex-1 h-8 text-xs bg-[#CCFF00] text-black hover:bg-[#CCFF00]/90"
                >
                  Add Exit
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setIsAddingCustom(false)}
                  className="h-8 text-xs border-[#2a3142] text-gray-400"
                >
                  Cancel
                </Button>
              </div>
            </div>
          )}

          {/* Minimum Exit Threshold */}
          <div className="p-4 bg-[#1a1f2e] rounded-xl border border-[#2a3142] space-y-3">
            <div className="flex justify-between items-center">
              <label className="text-xs text-gray-400">Minimum Exit Threshold</label>
              <span className="text-xs text-white font-mono">{inputs.minimumExitThreshold}%</span>
            </div>
            <p className="text-[10px] text-gray-500">
              Minimum % of property value that must be paid before developer allows resale
            </p>
          </div>
        </>
      )}
    </div>
  );
};
